packages:
  - "apps/*"

allowBuilds:
  '@swc/core': true
  esbuild: true

catalog:
  react: 19.2.3
  react-dom: 19.2.3

minimumReleaseAgeExclude:
  - '@applemusic-like-lyrics/core@0.4.1'
  - '@applemusic-like-lyrics/lyric@1.0.0'
  - '@applemusic-like-lyrics/react@0.4.1'
  - '@applemusic-like-lyrics/core@0.5.2'
  - '@applemusic-like-lyrics/lyric@1.0.2'
  - '@applemusic-like-lyrics/react@0.5.2'
