packages:
  - "apps/*"

allowBuilds:
  '@swc/core': true
  '@applemusic-like-lyrics/core': false
  '@applemusic-like-lyrics/vue': false
  '@parcel/watcher': false
  esbuild: true

catalog:
  react: 19.2.3
  react-dom: 19.2.3

minimumReleaseAgeExclude:
  - '@applemusic-like-lyrics/core@0.2.0'
  - '@applemusic-like-lyrics/vue@0.2.0'
  - '@applemusic-like-lyrics/core@0.4.1'
  - '@applemusic-like-lyrics/lyric@1.0.0'
  - '@applemusic-like-lyrics/react@0.4.1'
  - '@applemusic-like-lyrics/core@0.5.2'
  - '@applemusic-like-lyrics/lyric@1.0.2'
  - '@applemusic-like-lyrics/react@0.5.2'

patchedDependencies:
  '@applemusic-like-lyrics/core@0.2.0': apps/editor/patches/@applemusic-like-lyrics__core.patch
  '@types/wicg-file-system-access@2023.10.7': apps/editor/patches/@types__wicg-file-system-access.patch
