// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh-hans'

export type Locales =
	| 'en'
	| 'zh-hans'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	editor: {
		context: {
			shared: {
				/**
				 * 复​制
				 */
				copy: string
				/**
				 * 剪​切
				 */
				cut: string
				/**
				 * 粘​贴
				 */
				paste: string
			}
			blank: {
				/**
				 * 插​入​行
				 */
				insertLine: string
			}
			betweenLines: {
				/**
				 * 在​此​插​入​行
				 */
				insertLine: string
			}
			line: {
				/**
				 * 设​置​对​唱
				 */
				toggleDuet: string
				/**
				 * 设​置​背​景
				 */
				toggleBackground: string
				/**
				 * 合​并​行
				 */
				combineLines: string
				/**
				 * 在​前​插​入​行
				 */
				insertLineAbove: string
				/**
				 * 在​后​插​入​行
				 */
				insertLineBelow: string
				/**
				 * 克​隆​行
				 */
				duplicateLine: string
				/**
				 * 删​除​行
				 */
				deleteLine: string
			}
			syllable: {
				/**
				 * 在​前​插​入​音​节
				 */
				insertSylBefore: string
				/**
				 * 在​后​插​入​音​节
				 */
				insertSylAfter: string
				/**
				 * 在​此​拆​分​行
				 */
				breakLineAtSyl: string
				/**
				 * 删​除​音​节
				 */
				deleteSyl: string
			}
		}
		dragGhost: {
			/**
			 * {​{​复​制​行​}​}
			 */
			copyLine: string
			/**
			 * {​{​移​动​行​}​}
			 */
			moveLine: string
			/**
			 * {​{​复​制​音​节​}​}
			 */
			copySyllable: string
			/**
			 * {​{​移​动​音​节​}​}
			 */
			moveSyllable: string
		}
		emptyTip: {
			title: {
				/**
				 * 没​有​歌​词​行
				 */
				noLines: string
				/**
				 * 所​有​歌​词​行​均​为​空
				 */
				allLinesEmpty: string
			}
			detail: {
				/**
				 * 使​用​「​打​开​」​菜​单​加​载​内​容​，​或​右​键​空​白​处​插​入​新​行
				 */
				goLoadOrCreate: string
				/**
				 * 使​用​「​打​开​」​菜​单​加​载​内​容​，​或​在​内​容​视​图​下​编​辑
				 */
				goLoadOrEdit: string
			}
		}
		line: {
			/**
			 * 行​序​号
			 */
			index: string
			/**
			 * 双​击​以​切​换​时​轴​忽​略​状​态
			 */
			indexDbClickToToogleIgnore: string
			/**
			 * 书​签
			 */
			bookmark: string
			/**
			 * 对​唱
			 */
			duet: string
			/**
			 * 背​景
			 */
			background: string
			/**
			 * 应​用​至​逐​字​音​译
			 */
			applyRomanToSyl: string
			/**
			 * 从​逐​字​音​译​生​成
			 */
			generateRomanFromSyl: string
			/**
			 * 行​起​始​时​间
			 */
			startTime: string
			/**
			 * 行​结​束​时​间
			 */
			endTime: string
			/**
			 * 点​击​以​切​换​连​缀​结​束​时​间
			 */
			endTimeClickToConnect: string
			/**
			 * 双​击​以​编​辑
			 */
			endTimeDbClickToEdit: string
			/**
			 * 连​缀​结​束​时​间​至​下​一​行
			 */
			continueToNextLine: string
			/**
			 * 连​缀​结​束​时​间​至​下​行
			 */
			connectNext: string
			/**
			 * 添​加​音​节
			 */
			addSyllable: string
			fields: {
				/**
				 * 行​翻​译
				 */
				trans: string
				/**
				 * 行​音​译
				 */
				roman: string
			}
		}
		syllable: {
			/**
			 * 音​节​起​始​时​间
			 */
			startTime: string
			/**
			 * 音​节​结​束​时​间
			 */
			endTime: string
		}
		preview: {
			/**
			 * 重​载​ ​A​M​L​L
			 */
			reloadAmll: string
		}
	}
	titlebar: {
		/**
		 * 打​开
		 */
		open: string
		/**
		 * 打​开​文​件
		 */
		openTip: string
		openMenu: {
			/**
			 * 现​有​工​程
			 */
			project: string
			/**
			 * T​T​M​L​ ​文​件
			 */
			ttml: string
			/**
			 * 粘​贴​ ​T​T​M​L
			 */
			pasteTTML: string
			/**
			 * 导​入​纯​文​本
			 */
			importFromText: string
			/**
			 * 导​入​其​他​格​式
			 */
			importFromOtherFormats: string
			/**
			 * 空​项​目
			 */
			blank: string
		}
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 保​存​文​件
		 */
		saveTip: string
		saveMenu: {
			/**
			 * 另​存​为
			 */
			saveAs: string
			/**
			 * 导​出​为​项​目​文​件
			 */
			exportToProject: string
			/**
			 * 导​出​为​ ​T​T​M​L​ ​文​件
			 */
			exportToTTML: string
			/**
			 * 复​制​ ​T​T​M​L
			 */
			copyTTML: string
			/**
			 * 导​出​其​他​格​式
			 */
			exportToOtherFormats: string
		}
		/**
		 * 偏​好​设​置
		 */
		preferences: string
		/**
		 * 撤​销
		 */
		undo: string
		/**
		 * 重​做
		 */
		redo: string
		view: {
			/**
			 * 内​容
			 */
			content: string
			/**
			 * 时​轴
			 */
			timing: string
			/**
			 * 预​览
			 */
			preview: string
		}
		saveStatus: {
			/**
			 * 兼​容​读​写​模​式
			 */
			compatMode: string
			/**
			 * 未​授​予​写​入​权​限
			 */
			permissionNotGranted: string
			/**
			 * 已​保​存​于​ ​{​0​|​t​i​m​e​}
			 * @param {Date} 0
			 */
			savedAt: RequiredParams<'0|time'>
		}
	}
	ribbon: {
		content: {
			/**
			 * 内​容
			 */
			groupLabel: string
			/**
			 * 批​量​断​字
			 */
			batchSyllabify: string
			/**
			 * 打​开​批​量​断​字​侧​边​栏​，​将​多​行​歌​词​文​本​拆​分​为​音​节​。
			 */
			batchSyllabifyDesc: string
			/**
			 * 元​数​据
			 */
			metadata: string
			/**
			 * 打​开​元​数​据​侧​边​栏​，​编​辑​歌​词​文​件​元​数​据​。
			 */
			metadataDesc: string
			/**
			 * 查​找​替​换
			 */
			findReplace: string
			/**
			 * 打​开​查​找​替​换​对​话​框​，​在​歌​词​中​查​找​或​替​换​文​本​。
			 */
			findReplaceDesc: string
		}
		lineAttr: {
			/**
			 * 行​属​性
			 */
			groupLabel: string
			/**
			 * 对​唱​行
			 */
			duet: string
			/**
			 * 背​景​行
			 */
			background: string
			/**
			 * 时​轴​中​忽​略
			 */
			ignoreInTiming: string
			/**
			 * 续​至​下​行
			 */
			connectNext: string
			/**
			 * 开​始​时​间
			 */
			startTime: string
			/**
			 * 结​束​时​间
			 */
			endTime: string
			/**
			 * 持​续​时​长
			 */
			duration: string
		}
		syllableAttr: {
			/**
			 * 音​节​属​性
			 */
			groupLabel: string
			/**
			 * 开​始​时​间
			 */
			startTime: string
			/**
			 * 结​束​时​间
			 */
			endTime: string
			/**
			 * 持​续​时​长
			 */
			duration: string
			/**
			 * 占​位​拍
			 */
			placeholdingBeat: string
			/**
			 * 应​用​到​所​有​相​同​音​节
			 */
			applyToAllSameSyls: string
		}
		timeShift: {
			/**
			 * 时​移
			 */
			groupLabel: string
			/**
			 * 延​迟​测​试
			 */
			delayTest: string
			/**
			 * 延​迟
			 */
			delay: string
			/**
			 * 批​量​时​移
			 */
			batchTimeShift: string
			/**
			 * 打​开​批​量​时​移​对​话​框​，​调​整​多​个​音​节​或​行​的​时​间​戳​。
			 */
			batchTimeShiftDesc: string
		}
		view: {
			/**
			 * 视​图
			 */
			groupLabel: string
			/**
			 * 启​用​逐​字​音​译
			 */
			enableSylRoman: string
			/**
			 * 随​播​放​自​动​滚​动
			 */
			scrollWithPlayback: string
			/**
			 * 交​换​行​翻​译​音​译
			 */
			swapTranslateRoman: string
			/**
			 * 隐​藏​行​翻​译​音​译
			 */
			hideTranslateRoman: string
		}
		mark: {
			/**
			 * 标​记
			 */
			groupLabel: string
			/**
			 * 添​加​书​签
			 */
			addBookmark: string
			/**
			 * 移​除​书​签
			 */
			removeBookmark: string
			/**
			 * 在​选​定​行​或​音​节​上​添​加​或​移​除​书​签​。​书​签​可​以​用​于​标​记​重​要​的​部​分​，​且​不​会​导​出​到​歌​词​文​件​中​。
			 */
			bookmarkDesc: string
			/**
			 * 添​加​批​注
			 */
			addComment: string
			/**
			 * 移​除​全​部
			 */
			removeAll: string
			/**
			 * 移​除​全​文​所​有​行​和​音​节​的​书​签​与​批​注​。​您​可​以​稍​后​撤​销​。
			 */
			removeAllDesc: string
		}
		performance: {
			/**
			 * 性​能
			 */
			groupLabel: string
			/**
			 * 已​使​用
			 */
			usedHeapSize: string
			/**
			 * 已​分​配
			 */
			totalHeapSize: string
			/**
			 * 帧​速​率
			 */
			frameRate: string
		}
	}
	sidebar: {
		syllabify: {
			/**
			 * 批​量​断​字
			 */
			header: string
			/**
			 * 选​择​断​字​引​擎
			 */
			enginePlaceholder: string
			/**
			 * 断​字​引​擎
			 */
			engine: string
			/**
			 * 推​荐
			 */
			recommended: string
			/**
			 * 不​推​荐
			 */
			notRecommended: string
			/**
			 * 展​开
			 */
			expandDesc: string
			/**
			 * 收​起
			 */
			collapseDesc: string
			/**
			 * 自​定​义​规​则
			 */
			customRules: string
			/**
			 * 区​分​大​小​写
			 */
			caseSensitive: string
			/**
			 * 原​始​文​本
			 */
			originalTextPlaceholder: string
			/**
			 * 添​加​规​则
			 */
			addRule: string
			/**
			 * 现​有​音​节​属​性​将​丢​失​，​时​长​按​实​义​字​符​线​性​插​值
			 */
			sylDataLossWarn: string
			/**
			 * 应​用​到​选​定​行
			 */
			applyToSelectedLines: string
			/**
			 * 应​用​到​选​定​行​及​之​后
			 */
			applyToLinesAndAfter: string
			/**
			 * 应​用​到​所​有​行
			 */
			applyToAll: string
		}
		metadata: {
			/**
			 * 元​数​据
			 */
			header: string
			/**
			 * 不​使​用​模​板
			 */
			templatePlaceholder: string
			/**
			 * 元​数​据​字​段​模​板
			 */
			templateLabel: string
			templates: {
				lrc: {
					/**
					 * L​R​C​ ​元​数​据​模​板
					 */
					label: string
					/**
					 * 标​题
					 */
					ti: string
					/**
					 * 艺​术​家
					 */
					ar: string
					/**
					 * 专​辑
					 */
					al: string
					/**
					 * 作​者
					 */
					au: string
					/**
					 * 作​词
					 */
					lr: string
					/**
					 * 歌​词​创​建​者
					 */
					by: string
					/**
					 * 歌​词​创​建​工​具
					 */
					re: string
					/**
					 * 音​频​长​度
					 */
					len: string
					/**
					 * 长​度​格​式​应​为​ ​m​m​:​s​s​ ​或​ ​m​m​:​s​s​.​s​s​s
					 */
					lenValidationMsg: string
				}
				amll: {
					/**
					 * A​M​L​L​ ​T​T​M​L​ ​元​数​据​模​板
					 */
					label: string
					/**
					 * 歌​曲​名​称
					 */
					musicName: string
					/**
					 * 艺​术​家
					 */
					artists: string
					/**
					 * 专​辑​名
					 */
					album: string
					/**
					 * 网​易​云​音​乐​ ​I​D
					 */
					ncmMusicId: string
					/**
					 * Q​Q​ ​音​乐​ ​I​D
					 */
					qqMusicId: string
					/**
					 * S​p​o​t​i​f​y​ ​音​乐​ ​I​D
					 */
					spotifyId: string
					/**
					 * A​p​p​l​e​ ​M​u​s​i​c​ ​音​乐​ ​I​D
					 */
					appleMusicId: string
					/**
					 * I​S​R​C​ ​号
					 */
					isrc: string
					/**
					 * T​T​M​L​ ​作​者​ ​G​i​t​H​u​b​ ​U​I​D
					 */
					ttmlAuthorGithub: string
					/**
					 * T​T​M​L​ ​作​者​ ​G​i​t​H​u​b​ ​用​户​名
					 */
					ttmlAuthorGithubLogin: string
				}
			}
			/**
			 * 文​档
			 */
			documentBtn: string
			/**
			 * 添​加​全​部​预​设
			 */
			addAllPresets: string
			/**
			 * 键​名
			 */
			keyPlaceholder: string
			/**
			 * 清​除
			 */
			clear: string
			/**
			 * 添​加​字​段
			 */
			addField: string
		}
		preference: {
			/**
			 * 偏​好​设​置
			 */
			header: string
			/**
			 * 重​载​页​面​以​生​效
			 */
			refreshToTakeEffect: string
			resetConfirm: {
				/**
				 * 重​置​全​部​选​项
				 */
				header: string
				/**
				 * 确​定​要​将​所​有​选​项​恢​复​为​默​认​值​吗​？​此​操​作​不​可​撤​销​。
				 */
				message: string
				/**
				 * 重​置
				 */
				action: string
			}
			groups: {
				/**
				 * 数​据
				 */
				data: string
				/**
				 * 按​键
				 */
				key: string
				/**
				 * 内​容
				 */
				content: string
				/**
				 * 时​轴
				 */
				timing: string
				/**
				 * 频​谱
				 */
				spectrogram: string
				/**
				 * 兼​容​性
				 */
				compatibility: string
				/**
				 * 杂​项
				 */
				misc: string
				/**
				 * 关​于
				 */
				about: string
			}
			/**
			 * 实​验​性​选​项​，​可​能​不​稳​定
			 */
			experimentalWarning: string
			items: {
				/**
				 * 自​动​保​存
				 */
				autoSaveEnabled: string
				/**
				 * 授​予​写​入​权​限​后​，​定​时​保​存​至​文​件​系​统
				 */
				autoSaveEnabledDesc: string
				/**
				 * 自​动​保​存​间​隔
				 */
				autoSaveIntervalMinutes: string
				/**
				 * 自​动​保​存​触​发​的​时​间​间​隔​ ​(​分​钟​)
				 */
				autoSaveIntervalMinutesDesc: string
				/**
				 * 历​史​记​录​快​照​数
				 */
				maxUndoSteps: string
				/**
				 * 允​许​撤​销​的​最​大​操​作​步​数
				 */
				maxUndoStepsDesc: string
				/**
				 * 将​音​频​嵌​入​项​目​文​件
				 */
				packAudioToProject: string
				/**
				 * 将​音​频​文​件​打​包​在​项​目​文​件​中​，​以​便​归​档​或​分​享
				 */
				packAudioToProjectDesc: string
				/**
				 * 以​ ​T​T​M​L​ ​为​默​认​格​式
				 */
				ttmlAsDefault: string
				/**
				 * 新​建​和​保​存​文​档​时​默​认​使​用​ ​T​T​M​L​ ​而​非​ ​A​L​P​ ​格​式
				 */
				ttmlAsDefaultDesc: string
				/**
				 * 打​开​文​件​时​请​求​写​权​限
				 */
				askPermissionOnOpen: string
				/**
				 * 打​开​文​件​时​立​即​请​求​写​入​权​限​，​以​启​用​自​动​保​存
				 */
				askPermissionOnOpenDesc: string
				/**
				 * 按​键​绑​定
				 */
				keyBinding: string
				/**
				 * 打​开​快​捷​键​设​置​窗​口
				 */
				keyBindingDesc: string
				/**
				 * 设​置
				 */
				keyBindingAction: string
				/**
				 * m​a​c​O​S​ ​风​格​组​合​键
				 */
				macStyleShortcuts: string
				/**
				 * 使​用​ ​⌘​、​⌥​ ​等​符​号​展​示​组​合​键
				 */
				macStyleShortcutsDesc: string
				/**
				 * 音​频​按​键​跳​转​步​长
				 */
				audioSeekingStepMs: string
				/**
				 * 按​键​快​进​或​快​退​时​跳​转​的​时​长​ ​(​毫​秒​)
				 */
				audioSeekingStepMsDesc: string
				/**
				 * 交​换​翻​译​与​音​译​框​位​置
				 */
				swapTranslateRoman: string
				/**
				 * 在​内​容​视​图​将​音​译​框​置​于​左​侧​，​并​影​响​查​找​顺​序
				 */
				swapTranslateRomanDesc: string
				/**
				 * 隐​藏​翻​译​音​译​框
				 */
				hideTranslateRoman: string
				/**
				 * 隐​藏​内​容​视​图​中​的​翻​译​音​译​框
				 */
				hideTranslateRomanDesc: string
				/**
				 * 启​用​逐​字​音​译
				 */
				sylRomanEnabled: string
				/**
				 * 在​音​节​框​下​方​显​示​逐​字​音​译​，​并​支​持​查​找​替​换
				 */
				sylRomanEnabledDesc: string
				/**
				 * 全​局​延​时​补​偿
				 */
				globalLatencyMs: string
				/**
				 * 正​值​表​示​实​际​音​频​落​后​ ​(​毫​秒​)
				 */
				globalLatencyMsDesc: string
				/**
				 * 始​终​忽​略​背​景​行
				 */
				alwaysIgnoreBackground: string
				/**
				 * 在​时​轴​页​上​始​终​跳​过​背​景​行
				 */
				alwaysIgnoreBackgroundDesc: string
				/**
				 * 隐​藏​行​时​间​戳
				 */
				hideLineTiming: string
				/**
				 * 自​动​从​音​节​生​成​行​时​间​戳
				 */
				hideLineTimingDesc: string
				/**
				 * 随​播​放​自​动​滚​动
				 */
				scrollWithPlayback: string
				/**
				 * 时​轴​视​图​中​随​播​放​进​度​自​动​滚​动
				 */
				scrollWithPlaybackDesc: string
				/**
				 * 进​度​条​高​亮​选​中​行
				 */
				highlightSelectedLineOnProgress: string
				/**
				 * 在​进​度​波​形​条​上​高​亮​显​示​当​前​选​中​行​的​时​间​段
				 */
				highlightSelectedLineOnProgressDesc: string
				/**
				 * 兼​容​性​报​告
				 */
				compatibilityReport: string
				/**
				 * 打​开​兼​容​性​报​告​窗​口
				 */
				compatibilityReportDesc: string
				/**
				 * 打​开
				 */
				compatibilityReportAction: string
				/**
				 * 启​动​时​报​告​兼​容​性​问​题
				 */
				notifyCompatIssuesOnStartup: string
				/**
				 * 在​启​动​时​若​发​现​问​题​，​显​示​兼​容​性​报​告​对​话​框
				 */
				notifyCompatIssuesOnStartupDesc: string
				/**
				 * 重​置​全​部​选​项
				 */
				resetAll: string
				/**
				 * 将​所​有​选​项​恢​复​为​默​认​值
				 */
				resetAllDesc: string
				/**
				 * 语​言
				 */
				language: string
				/**
				 * 选​择​界​面​显​示​语​言
				 */
				languageDesc: string
				/**
				 * 重​置
				 */
				resetAllAction: string
				/**
				 * 关​于​ ​{​0​}
				 * @param {unknown} 0
				 */
				aboutApp: RequiredParams<'0'>
				/**
				 * 打​开​软​件​版​本​信​息​窗​口
				 */
				aboutAppDesc: string
				/**
				 * 关​于
				 */
				aboutAppAction: string
				/**
				 * G​i​t​H​u​b​ ​仓​库
				 */
				githubRepo: string
				/**
				 * 访​问​源​代​码​仓​库​页​面
				 */
				githubRepoDesc: string
				/**
				 * 前​往
				 */
				githubRepoAction: string
				/**
				 * 侧​边​栏​宽​度
				 */
				sidebarWidth: string
				/**
				 * 侧​边​栏​的​默​认​宽​度​ ​(​像​素​)
				 */
				sidebarWidthDesc: string
				/**
				 * 频​谱​图​高​度
				 */
				spectrogramHeight: string
				/**
				 * 频​谱​图​的​高​度​ ​(​像​素​)
				 */
				spectrogramHeightDesc: string
				/**
				 * 配​色​方​案
				 */
				spectrogramColor: string
				/**
				 * 选​择​预​设​色​彩​方​案​或​自​定​义​渐​变
				 */
				spectrogramColorDesc: string
			}
		}
	}
	player: {
		/**
		 * 选​择​音​频​文​件
		 */
		chooseAudioFile: string
		/**
		 * 播​放​选​项
		 */
		playOptions: string
		/**
		 * 使​用​鼠​标​滚​轮​调​整​音​量
		 */
		playOptionsWheel: string
		/**
		 * 音​量
		 */
		volume: string
		/**
		 * 速​率
		 */
		rate: string
		/**
		 * 重​置​到​ ​{​0​}
		 * @param {unknown} 0
		 */
		resetTo: RequiredParams<'0'>
		/**
		 * 播​放
		 */
		play: string
		/**
		 * 暂​停
		 */
		pause: string
		/**
		 * 显​示​频​谱​图
		 */
		showSpectrogram: string
		/**
		 * 隐​藏​频​谱​图
		 */
		hideSpectrogram: string
		/**
		 * 频​谱​图​不​可​用
		 */
		spectrogramUnavailable: string
		/**
		 * 所​有​支​持​的​音​频​格​式
		 */
		allSupportedFormats: string
		failedToLoadAudio: {
			/**
			 * 加​载​音​频​失​败
			 */
			summary: string
			/**
			 * 文​件​访​问​被​用​户​或​平​台​拒​绝
			 */
			detailAborted: string
		}
		/**
		 * 成​功​加​载​音​频
		 */
		loadAudioSuccess: string
	}
	spectrogram: {
		emptyTip: {
			/**
			 * 没​有​音​频​数​据
			 */
			title: string
			/**
			 * 加​载​音​频​文​件​后​将​渲​染​频​谱​图
			 */
			detail: string
		}
	}
	compat: {
		dialog: {
			/**
			 * 兼​容​性​报​告
			 */
			header: string
			/**
			 * 不​支​持
			 */
			notSupported: string
			/**
			 * 未​提​供​说​明
			 */
			noReasonProvided: string
			/**
			 * 未​提​供​可​能​导​致​的​问​题
			 */
			noImpactProvided: string
			/**
			 * 启​动​时​不​再​检​查​兼​容​性
			 */
			dontCheckOnStartup: string
			/**
			 * 确​认
			 */
			proceed: string
		}
		sharedReasons: {
			/**
			 * 未​在​安​全​上​下​文​中​运​行​。​需​要​ ​H​T​T​P​S​ ​或​从​本​地​回​环​访​问​。
			 */
			insecureContext: string
		}
		clipboard: {
			/**
			 * 剪​贴​板​ ​A​P​I
			 */
			name: string
			/**
			 * 剪​贴​板​ ​A​P​I​ ​(​C​l​i​p​b​o​a​r​d​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​系​统​剪​贴​板​的​内​容​。
			 */
			description: string
			/**
			 * 剪​切​复​制​粘​贴​歌​词​行​与​音​节​、​复​制​和​粘​贴​ ​T​T​M​L​ ​功​能​不​可​用​。
			 */
			impact: string
			/**
			 * 浏​览​器​不​支​持​剪​贴​板​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​6​、​F​i​r​e​f​o​x​ ​1​2​5​、​S​a​f​a​r​i​ ​1​3​.​1​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
		}
		fileSystem: {
			/**
			 * 文​件​系​统​ ​A​P​I
			 */
			name: string
			/**
			 * 文​件​系​统​ ​A​P​I​ ​(​F​i​l​e​ ​S​y​s​t​e​m​ ​A​P​I​)​ ​允​许​网​页​在​用​户​授​权​后​读​写​磁​盘​上​的​文​件​，​提​供​接​近​原​生​的​文​件​操​作​能​力​。
			 */
			description: string
			/**
			 * 保​存​文​件​时​无​法​直​接​写​入​，​而​是​通​过​浏​览​器​下​载​；​自​动​保​存​不​可​用​。
			 */
			impact: string
			/**
			 * 浏​览​器​不​支​持​文​件​系​统​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​8​6​ ​及​以​上​版​本​中​支​持​，​F​i​r​e​f​o​x​ ​和​ ​S​a​f​a​r​i​ ​暂​不​支​持​。
			 */
			apiNotSupported: string
		}
		mediaSession: {
			/**
			 * 媒​体​会​话​ ​A​P​I
			 */
			name: string
			/**
			 * 媒​体​会​话​ ​(​M​e​d​i​a​ ​S​e​s​s​i​o​n​)​ ​允​许​网​页​自​定​义​媒​体​通​知​和​响​应​媒​体​键​事​件​。
			 */
			description: string
			/**
			 * 将​不​能​从​系​统​媒​体​控​制​界​面​（​如​锁​屏​界​面​或​通​知​中​心​）​控​制​媒​体​播​放​。
			 */
			impact: string
			/**
			 * 浏​览​器​不​支​持​媒​体​会​话​相​关​的​ ​A​P​I​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​7​2​、​F​i​r​e​f​o​x​ ​8​2​、​S​a​f​a​r​i​ ​1​5​ ​或​以​上​版​本​中​支​持​。​F​i​r​e​f​o​x​ ​A​n​d​r​o​i​d​ ​目​前​不​支​持​。
			 */
			apiNotSupported: string
		}
		sharedArrayBuffer: {
			/**
			 * 共​享​内​存​缓​冲​区
			 */
			name: string
			/**
			 * 共​享​内​存​缓​冲​区​ ​(​S​h​a​r​e​d​ ​A​r​r​a​y​ ​B​u​f​f​e​r​)​ ​允​许​在​多​个​线​程​间​高​效​共​享​数​据​。
			 */
			description: string
			/**
			 * 频​谱​图​功​能​不​可​用​。
			 */
			impact: string
			/**
			 * 浏​览​器​不​支​持​ ​S​h​a​r​e​d​A​r​r​a​y​B​u​f​f​e​r​。​此​ ​A​P​I​ ​在​ ​C​h​r​o​m​i​u​m​ ​6​8​、​F​i​r​e​f​o​x​ ​7​9​、​S​a​f​a​r​i​ ​1​5​.​2​ ​或​以​上​版​本​中​支​持​。
			 */
			apiNotSupported: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​请​联​系​部​署​方​提​供​对​应​的​ ​H​T​T​P​ ​响​应​头​，​或​调​整​构​建​选​项​以​启​用​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​方​式​实​现​的​跨​源​隔​离​。
			 */
			coiRequired: string
			/**
			 * 未​启​用​跨​源​隔​离​ ​(​C​O​O​P​/​C​O​E​P​)​。​此​部​署​已​尝​试​通​过​ ​S​e​r​v​i​c​e​ ​W​o​r​k​e​r​ ​启​用​跨​源​隔​离​。​若​未​生​效​，​请​尝​试​刷​新​页​面​。
			 */
			coiWorkaround: string
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维​基​百​科
			 */
			wikipedia: string
			/**
			 * 官​方​文​档
			 */
			officialDoc: string
		}
		alp: {
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​工​程
			 */
			name: string
			/**
			 * A​M​L​L​ ​E​d​i​t​o​r​ ​的​项​目​文​件​格​式​，​内​嵌​音​频​文​件​和​歌​词​数​据​，​适​合​项​目​保​存​和​传​输​。
			 */
			description: string
		}
		ttml: {
			/**
			 * A​M​L​L​ ​T​T​M​L
			 */
			name: string
			/**
			 * 基​于​ ​W​3​C​ ​T​T​M​L​ ​标​准​的​歌​词​格​式​，​遵​循​ ​A​M​L​L​ ​T​T​M​L​ ​歌​词​格​式​规​范​。
			 */
			description: string
		}
		lrc: {
			/**
			 * 基​本​ ​L​R​C
			 */
			name: string
			/**
			 * 最​常​见​的​歌​词​格​式​。​支​持​行​时​间​戳​，​不​支​持​逐​字​时​间​戳​。​此​处​指​基​本​ ​L​R​C​ ​格​式​，​若​要​导​入​基​于​ ​L​R​C​ ​的​扩​展​格​式​，​请​选​择​对​应​扩​展​格​式​选​项​。
			 */
			description: string
		}
		lrcA2: {
			/**
			 * L​R​C​ ​A​2​ ​扩​展
			 */
			name: string
			/**
			 * 基​于​ ​L​R​C​ ​的​扩​展​格​式​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​最​早​由​ ​A​2​ ​M​e​d​i​a​ ​P​l​a​y​e​r​ ​提​出​。
			 */
			description: string
		}
		yrc: {
			/**
			 * 网​易​云​逐​字
			 */
			name: string
			/**
			 * 网​易​云​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		qrc: {
			/**
			 * Q​Q​ ​音​乐​逐​字
			 */
			name: string
			/**
			 * Q​Q​ ​音​乐​的​私​有​逐​字​歌​词​格​式​。​支​持​行​时​间​戳​和​逐​字​时​间​戳​。
			 */
			description: string
		}
		lyl: {
			/**
			 * L​y​r​i​c​i​f​y​ ​L​i​n​e​s
			 */
			name: string
			/**
			 * L​y​r​i​c​i​f​y​ ​的​私​有​行​时​间​戳​歌​词​格​式​，​不​支​持​逐​字​时​间​戳​。
			 */
			description: string
		}
		lys: {
			/**
			 * L​y​r​i​c​i​f​y​ ​S​y​l​l​a​b​l​e
			 */
			name: string
			/**
			 * L​y​r​i​c​i​f​y​ ​的​私​有​逐​字​时​间​戳​歌​词​格​式​，​支​持​逐​字​、​背​景​与​对​唱​。
			 */
			description: string
		}
		lqe: {
			/**
			 * L​y​r​i​c​i​f​y​ ​快​速​导​出
			 */
			name: string
			/**
			 * L​y​r​i​c​i​f​y​ ​的​私​有​快​速​导​出​格​式​，​在​ ​L​y​r​i​c​i​f​y​ ​S​y​l​l​a​b​l​e​ ​逐​字​基​础​上​支​持​翻​译​与​音​译​。
			 */
			description: string
		}
		spl: {
			/**
			 * 椒​盐​音​乐​逐​字
			 */
			name: string
			/**
			 * 椒​盐​音​乐​的​私​有​格​式​，​基​于​ ​L​R​C​ ​扩​展​，​支​持​行​时​间​戳​和​逐​字​时​间​戳​，​并​支​持​翻​译​。​由​于​规​则​繁​杂​，​可​能​不​完​全​可​用​。
			 */
			description: string
		}
	}
	file: {
		/**
		 * 所​有​支​持​的​格​式
		 */
		allSupportedFormats: string
		/**
		 * 未​命​名
		 */
		untitled: string
		/**
		 * 成​功​加​载​文​件
		 */
		loaded: string
		failedToReadErr: {
			/**
			 * 读​取​文​件​失​败
			 */
			summary: string
			/**
			 * 不​支​持​的​文​件​类​型​：​{​0​}
			 * @param {unknown} 0
			 */
			typeNotSupported: RequiredParams<'0'>
		}
		dataDropConfirm: {
			/**
			 * 您​有​未​保​存​的​工​作
			 */
			header: string
			/**
			 * 如​果​继​续​，​所​有​未​保​存​的​更​改​将​会​丢​失​。​此​操​作​不​可​撤​销​。
			 */
			message: string
			/**
			 * 继​续
			 */
			acceptLabel: string
		}
		/**
		 * 成​功​加​载​文​件
		 */
		loadFileSuccess: string
		failedToLoadErr: {
			/**
			 * 加​载​文​件​失​败
			 */
			summary: string
			/**
			 * 文​件​访​问​被​用​户​或​平​台​拒​绝
			 */
			detailAborted: string
		}
		/**
		 * 剪​贴​板​为​空
		 */
		clipboardIsEmptyErr: string
		/**
		 * 从​剪​贴​板​导​入​ ​T​T​M​L​ ​失​败
		 */
		failedToPasteTTML: string
		/**
		 * 复​制​ ​T​T​M​L​ ​到​剪​贴​板​失​败
		 */
		failedToCopyTTML: string
		/**
		 * 成​功​从​剪​贴​板​导​入​ ​T​T​M​L
		 */
		pasteTTMLSuccess: string
		/**
		 * 成​功​复​制​ ​T​T​M​L​ ​到​剪​贴​板
		 */
		copyTTMLSuccess: string
		/**
		 * 成​功​创​建​空​项​目
		 */
		newBlankProjectSuccess: string
		failedBlankProject: {
			/**
			 * 创​建​空​项​目​失​败
			 */
			summary: string
			/**
			 * 操​作​被​用​户​拒​绝
			 */
			detailAborted: string
		}
		/**
		 * 成​功​保​存​文​件
		 */
		saveFileSuccess: string
		failedToSaveErr: {
			/**
			 * 保​存​文​件​失​败
			 */
			summary: string
			/**
			 * 文​件​写​入​被​用​户​或​平​台​拒​绝
			 */
			detailAborted: string
		}
		/**
		 * 成​功​另​存​为​文​件
		 */
		saveAsSuccess: string
		failedToSaveAsErr: {
			/**
			 * 另​存​为​文​件​失​败
			 */
			summary: string
			/**
			 * 文​件​写​入​被​用​户​或​平​台​拒​绝
			 */
			detailAborted: string
		}
	}
	find: {
		/**
		 * 查​找​替​换
		 */
		header: string
		mode: {
			/**
			 * 查​找
			 */
			find: string
			/**
			 * 替​换
			 */
			replace: string
		}
		placeholder: {
			/**
			 * 查​找​内​容
			 */
			find: string
			/**
			 * 替​换​为
			 */
			replace: string
		}
		/**
		 * 更​多​选​项
		 */
		moreOptionSwitch: string
		/**
		 * 匹​配​选​项
		 */
		optionsHeader: string
		options: {
			/**
			 * 区​分​大​小​写
			 */
			caseSensitive: string
			/**
			 * 全​字​匹​配
			 */
			wholeWord: string
			/**
			 * 全​字​段​匹​配
			 */
			wholeField: string
			/**
			 * 跨​音​节​匹​配
			 */
			crossSyl: string
			/**
			 * 正​则​表​达​式
			 */
			useRegex: string
			/**
			 * 循​环​搜​索
			 */
			loopSearch: string
		}
		/**
		 * 匹​配​范​围
		 */
		scopeHeader: string
		scope: {
			/**
			 * 音​节​内​容
			 */
			sylContent: string
			/**
			 * 音​节​音​译
			 */
			sylRoman: string
			/**
			 * 翻​译
			 */
			trans: string
			/**
			 * 音​译
			 */
			roman: string
			/**
			 * 行​音​译
			 */
			lineRoman: string
			/**
			 * 行​翻​译
			 */
			lineTrans: string
		}
		actions: {
			/**
			 * 替​换
			 */
			replace: string
			/**
			 * 全​部​替​换
			 */
			replaceAll: string
			/**
			 * 查​找​上​一​项
			 */
			findPrev: string
			/**
			 * 查​找​下​一​项
			 */
			findNext: string
		}
		infLoopErr: {
			/**
			 * 搜​索​失​败
			 */
			summary: string
			/**
			 * 发​生​死​循​环​。​请​前​往​反​馈​此​问​题​。
			 */
			detail: string
		}
		noResultWarn: {
			/**
			 * 找​不​到​结​果
			 */
			summary: string
			/**
			 * 在​所​选​范​围​内​文​档​为​空​。
			 */
			detailEmpty: string
			/**
			 * 全​文​搜​索​完​毕​，​未​找​到​匹​配​项​。
			 */
			detailNoMatch: string
			/**
			 * 已​到​达​文​档​末​端​，​无​匹​配​项​。​
		​启​用​循​环​搜​索​可​从​头​开​始​继​续​搜​索​。
			 */
			detailNoMatchEnd: string
		}
		replaceSuccess: {
			/**
			 * 替​换​成​功
			 */
			summary: string
			/**
			 * 共​替​换​了​ ​{​0​}​ ​处​匹​配​项​。
			 * @param {number} 0
			 */
			detail: RequiredParams<'0'>
		}
	}
	hotkey: {
		/**
		 * 按​键​绑​定
		 */
		dialogHeader: string
		/**
		 * 未​绑​定
		 */
		notBinded: string
		btns: {
			/**
			 * 添​加
			 */
			add: string
			/**
			 * 移​除
			 */
			del: string
			/**
			 * 重​置​为​默​认
			 */
			reset: string
		}
		groupTitles: {
			/**
			 * 文​件​操​作
			 */
			file: string
			/**
			 * 视​图​与​界​面
			 */
			view: string
			/**
			 * 编​辑​操​作
			 */
			editing: string
			/**
			 * 时​轴
			 */
			timing: string
			/**
			 * 音​频​控​制
			 */
			audio: string
		}
		commands: {
			/**
			 * 打​开
			 */
			open: string
			/**
			 * 保​存
			 */
			save: string
			/**
			 * 另​存​为
			 */
			saveAs: string
			/**
			 * 新​建​空​项​目
			 */
			'new': string
			/**
			 * 导​出​到​剪​贴​板
			 */
			exportToClipboard: string
			/**
			 * 从​剪​贴​板​导​入
			 */
			importFromClipboard: string
			/**
			 * 切​换​到​内​容​视​图
			 */
			switchToContent: string
			/**
			 * 切​换​到​时​轴​视​图
			 */
			switchToTiming: string
			/**
			 * 切​换​到​预​览​视​图
			 */
			switchToPreview: string
			/**
			 * 偏​好​设​置
			 */
			preferences: string
			/**
			 * 批​量​断​字
			 */
			batchSplitText: string
			/**
			 * 元​数​据
			 */
			metadata: string
			/**
			 * 批​量​时​移
			 */
			batchTimeShift: string
			/**
			 * 撤​销
			 */
			undo: string
			/**
			 * 重​做
			 */
			redo: string
			/**
			 * 书​签
			 */
			bookmark: string
			/**
			 * 查​找
			 */
			find: string
			/**
			 * 替​换
			 */
			replace: string
			/**
			 * 删​除
			 */
			'delete': string
			/**
			 * 全​选​所​有​行
			 */
			selectAllLines: string
			/**
			 * 全​选​所​有​音​节
			 */
			selectAllSyls: string
			/**
			 * 拆​分​行
			 */
			breakLine: string
			/**
			 * 设​为​对​唱​行
			 */
			duet: string
			/**
			 * 设​为​背​景​行
			 */
			background: string
			/**
			 * 续​至​下​行
			 */
			connectNextLine: string
			/**
			 * 合​并​行
			 */
			combineLines: string
			/**
			 * 上​一​行
			 */
			goPrevLine: string
			/**
			 * 上​一​音​节
			 */
			goPrevSyl: string
			/**
			 * 上​一​音​节​并​播​放
			 */
			goPrevSylnPlay: string
			/**
			 * 下​一​行
			 */
			goNextLine: string
			/**
			 * 下​一​音​节
			 */
			goNextSyl: string
			/**
			 * 下​一​音​节​并​播​放
			 */
			goNextSylnPlay: string
			/**
			 * 播​放​当​前​音​节
			 */
			playCurrSyl: string
			/**
			 * 标​记​开​始​时​间
			 */
			markBegin: string
			/**
			 * 标​记​连​缀​时​间
			 */
			markEndBegin: string
			/**
			 * 标​记​结​束​时​间
			 */
			markEnd: string
			/**
			 * 选​择​媒​体
			 */
			chooseMedia: string
			/**
			 * 快​退
			 */
			seekBackward: string
			/**
			 * 增​大​音​量
			 */
			volumeUp: string
			/**
			 * 播​放​/​暂​停​音​频
			 */
			playPauseAudio: string
			/**
			 * 快​进
			 */
			seekForward: string
			/**
			 * 减​小​音​量
			 */
			volumeDown: string
		}
		keyNames: {
			/**
			 * 空​格
			 */
			space: string
		}
	}
	syllabify: {
		engines: {
			basic: {
				/**
				 * 基​本​断​字
				 */
				name: string
				/**
				 * 对​西​文​按​词​拆​分​，​对​于​ ​C​J​K​ ​按​字​拆​分​。​若​有​自​定​义​规​则​，​将​对​拆​分​后​的​词​应​用​，​已​拆​分​的​词​不​会​合​并​。
				 */
				description: string
			}
			jaBasic: {
				/**
				 * 日​语​基​本​断​字
				 */
				name: string
				/**
				 * 针​对​日​语​拗​音​等​做​专​门​处​理​。​若​有​自​定​义​规​则​，​将​优​先​提​取​自​定​义​拆​分​，​其​余​部​分​按​规​则​拆​分​。
				 */
				description: string
			}
			prosodic: {
				/**
				 * 英​语​ ​(​P​r​o​s​o​d​i​c​)
				 */
				name: string
				/**
				 * 将​ ​S​U​B​T​L​E​X​u​s​ ​作​为​语​料​，​由​ ​P​r​o​s​o​d​i​c​ ​根​据​读​音​进​行​音​节​划​分​并​匹​配​回​拼​写​得​到​词​典​，​高​频​词​经​人​工​校​对​。​未​命​中​的​词​将​回​退​至​ ​C​o​m​p​r​o​m​i​s​e​。
				 */
				description: string
			}
			silabas: {
				/**
				 * 西​班​牙​语​ ​(​S​i​l​a​b​a​s​)
				 */
				name: string
				/**
				 * 由​ ​S​i​l​a​b​a​s​.​j​s​ ​库​提​供​的​西​班​牙​语​正​字​法​音​节​切​分​，​基​于​现​代​语​料​。​移​植​自​ ​U​L​P​G​C​ ​S​i​l​a​b​e​a​d​o​r​ ​T​I​P​ ​C​+​+​ ​实​现​。
				 */
				description: string
			}
			silabeador: {
				/**
				 * 西​班​牙​语​ ​(​S​i​l​a​b​e​a​d​o​r​)
				 */
				name: string
				/**
				 * 由​ ​S​i​l​a​b​e​a​d​o​r​ ​库​提​供​，​主​要​基​于​黄​金​时​代​语​料​的​西​班​牙​语​正​字​法​音​节​切​分​，​与​现​代​规​则​有​一​定​出​入​。​通​过​ ​P​y​o​d​i​d​e​ ​运​行​，​初​次​加​载​可​能​较​慢​。
				 */
				description: string
			}
			compromise: {
				/**
				 * 英​语​ ​(​C​o​m​p​r​o​m​i​s​e​)
				 */
				name: string
				/**
				 * 由​ ​C​o​m​p​r​o​m​i​s​e​ ​库​提​供​的​纯​正​字​法​英​语​音​节​拆​分​。​由​于​英​语​发​音​不​规​则​情​况​较​多​，​请​优​先​使​用​ ​P​r​o​s​o​d​i​c​ ​引​擎​。
				 */
				description: string
			}
			syllabifyFr: {
				/**
				 * 法​语​ ​(​S​y​l​l​a​b​i​f​y​-​f​r​)
				 */
				name: string
				/**
				 * 由​ ​S​y​l​l​a​b​i​f​y​-​f​r​ ​库​提​供​的​正​字​法​法​语​音​节​划​分​。
				 */
				description: string
			}
			syllabify: {
				/**
				 * 俄​语​ ​(​S​y​l​l​a​b​i​f​y​)
				 */
				name: string
				/**
				 * 由​ ​S​y​l​l​a​b​i​f​y​ ​库​提​供​的​正​字​法​俄​语​音​节​划​分​。
				 */
				description: string
			}
			none: {
				/**
				 * 不​断​字
				 */
				name: string
				/**
				 * 不​进​行​音​节​划​分​，​将​每​行​的​所​有​文​本​合​并​为​一​个​音​节​。​自​定​义​规​则​不​产​生​作​用​。​适​用​于​制​作​逐​行​歌​词​。
				 */
				description: string
			}
		}
	}
	components: {
		confirmDialog: {
			/**
			 * 取​消
			 */
			cancel: string
			/**
			 * 继​续
			 */
			'continue': string
		}
		/**
		 * 当​前​视​图​无​内​容​可​显​示
		 */
		emptyTipDefault: string
	}
	importFromText: {
		/**
		 * 从​纯​文​本​导​入
		 */
		header: string
		modes: {
			/**
			 * 分​别​输​入
			 */
			separate: string
			/**
			 * 歌​词​原​文​、​翻​译​、​音​译​分​别​在​不​同​的​文​本​框​中​输​入​。​相​同​位​置​的​行​为​一​组​。
			 */
			separateDesc: string
			/**
			 * 交​错​行
			 */
			interleaved: string
			/**
			 * 歌​词​原​文​与​翻​译​、​音​译​行​混​合​交​错​排​列​。​每​连​续​的​数​行​为​一​组​。
			 */
			interleavedDesc: string
		}
		fields: {
			/**
			 * 原​文
			 */
			original: string
			/**
			 * （​保​留​现​有​行​）
			 */
			keepCurrentLinesTip: string
			/**
			 * 翻​译
			 */
			trans: string
			/**
			 * 音​译
			 */
			roman: string
			/**
			 * 至​少​提​供​一​项
			 */
			atLeastProvideOne: string
		}
		toolBtns: {
			/**
			 * 移​除​时​间​戳
			 */
			removeTimestamps: string
			/**
			 * 移​除​空​白​行
			 */
			removeEmptyLines: string
			/**
			 * 规​范​化​空​格
			 */
			normalizeSpaces: string
			/**
			 * 首​字​母​大​写
			 */
			capitalizeFirstLetter: string
			/**
			 * 去​除​尾​标​点
			 */
			removeTrailingPunc: string
		}
		lineOrder: {
			/**
			 * 行​顺​序​设​置
			 */
			header: string
			/**
			 * 当​前​循​环​节​共​ ​{​0​}​ ​行
			 * @param {number} 0
			 */
			cycleLengthHint: RequiredParams<'0'>
			/**
			 * 原​文​行
			 */
			original: string
			/**
			 * 翻​译​行
			 */
			trans: string
			/**
			 * 音​译​行
			 */
			roman: string
			/**
			 * 组​间​空​行​数
			 */
			emptyLineCount: string
		}
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 导​入
		 */
		action: string
	}
	importFromOtherFormats: {
		/**
		 * 从​其​他​歌​词​格​式​导​入
		 */
		header: string
		/**
		 * 未​提​供​说​明
		 */
		noDescriptionProvided: string
		/**
		 * 显​示​示​例
		 */
		showExamples: string
		/**
		 * 从​文​件​打​开
		 */
		fromFile: string
		/**
		 * 示​例​格​式
		 */
		exampleLabel: string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 导​入
		 */
		'import': string
		/**
		 * 请​在​左​侧​选​择​格​式
		 */
		requireSelectFormat: string
	}
	about: {
		/**
		 * 关​于
		 */
		header: string
		/**
		 * 版​本
		 */
		version: string
		/**
		 * 基​于​ ​V​u​e​ ​的​开​源​逐​音​节​歌​词​编​辑​器​，​可​与​ ​A​M​L​L​ ​生​态​软​件​协​作​，​目​标​成​为​ ​A​M​L​L​ ​T​T​M​L​ ​T​o​o​l​ ​的​继​任​者​。​
	​开​发​不​易​，​不​妨​点​个​免​费​的​ ​s​t​a​r​ ​吧​！
		 */
		description: string
		/**
		 * G​i​t​H​u​b​ ​仓​库
		 */
		githubBtn: string
		/**
		 * 展​开​详​细​信​息
		 */
		detailBtn: string
		detail: {
			/**
			 * 版​本​号
			 */
			version: string
			/**
			 * 构​建​通​道
			 */
			channel: string
			/**
			 * 提​交​哈​希
			 */
			hash: string
			/**
			 * 构​建​时​间
			 */
			buildTime: string
			/**
			 * A​M​L​L​ ​核​心​版​本
			 */
			amllCoreVersion: string
			/**
			 * A​M​L​L​ ​V​u​e​ ​版​本
			 */
			amllVueVersion: string
			/**
			 * 未​指​定
			 */
			notSpecified: string
		}
	}
	batchTimeShift: {
		/**
		 * 批​量​时​移
		 */
		header: string
		/**
		 * 推​迟​为​正​，​提​前​为​负
		 */
		signHint: string
		/**
		 * 应​用​到​选​定​音​节
		 */
		applyToSyl: string
		/**
		 * 应​用​到​选​定​行
		 */
		applyToLine: string
		/**
		 * 应​用​到​全​文
		 */
		applyToAll: string
	}
	/**
	 * ╭​─​─​─​─​─​─​─​─​─​─​╮​ ​ ​ ​ ​ ​ ​ ​╶​╴​ ​ ​ ​ ​┌​─​╴​ ​ ​╶​─​┐​┌​─​┐​ ​ ​ ​ ​┌​─​┐​ ​ ​ ​ ​ ​ ​┌​─​─​─​─​─​┐​ ​ ​ ​ ​┌​─​┐​┌​─​┐​
​│​ ​━​━​━​━​━​━​ ​ ​ ​│​ ​ ​ ​ ​ ​ ​╱​ ​ ​╲​ ​ ​ ​│​ ​ ​╲​╱​ ​ ​│​│​ ​│​ ​ ​ ​ ​│​ ​│​ ​ ​ ​ ​ ​ ​│​ ​┌​─​─​─​┘​ ​ ​ ​ ​│​ ​│​└​─​┘​┌​─​┐​
​│​ ​ ​ ​━​━​━​━​━​ ​ ​│​ ​ ​ ​ ​ ​╱​ ​╱​╲​ ​╲​ ​ ​│​ ​╷​ ​ ​╷​ ​│​│​ ​│​ ​ ​ ​ ​│​ ​│​ ​ ​ ​ ​ ​ ​│​ ​└​─​─​┐​ ​╭​─​─​─​┘​ ​│​┌​─​┐​│​ ​└​┐​╭​─​─​─​─​─​╮​╭​─​─​─​┐​
​│​ ​|​>​ ​━​━​━​ ​•​ ​│​ ​ ​ ​ ​╱​ ​╶​─​─​╴​ ​╲​ ​│​ ​│​╲​╱​│​ ​│​│​ ​│​ ​ ​ ​ ​│​ ​│​ ​ ​ ​ ​ ​ ​│​ ​┌​─​─​┘​ ​│​ ​╭​─​╮​ ​│​│​ ​│​│​ ​┌​┘​│​ ​╭​─​╮​ ​│​│​ ​┌​─​┘​
​│​ ​ ​ ​━​━​━​━​━​ ​ ​│​ ​ ​ ​╱​ ​╱​ ​ ​ ​ ​╲​ ​╲​│​ ​│​ ​ ​│​ ​│​│​ ​└​─​─​─​┐​│​ ​└​─​─​─​┐​ ​ ​│​ ​└​─​─​─​┐​│​ ​╰​─​╯​ ​│​│​ ​│​│​ ​└​┐​│​ ​╰​─​╯​ ​│​│​ ​│​
​╰​─​─​─​─​─​─​─​─​─​─​╯​ ​ ​ ​─​╴​ ​ ​ ​ ​ ​ ​╶​─​└​─​┘​ ​ ​└​─​┘​└​─​─​─​─​─​┘​└​─​─​─​─​─​┘​ ​ ​└​─​─​─​─​─​┘​╰​─​─​─​─​─​┘​└​─​┘​╰​─​─​┘​╰​─​─​─​─​─​╯​└​─​┘​
​
​喜​欢​您​来​！​
​
​项​目​地​址​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​a​m​l​l​-​d​e​v​/​a​m​l​l​-​e​d​i​t​o​r​
​　​　​　​　​ ​ ​以​ ​A​G​P​L​v​3​ ​o​n​l​y​ ​许​可​证​开​源​
​
​友​情​链​接​:​ ​A​M​L​L​ ​H​o​m​e​p​a​g​e​ ​ ​h​t​t​p​s​:​/​/​a​m​l​l​.​d​e​v​/​
​　​　​　​　​ ​ ​A​M​L​L​ ​T​T​M​L​ ​D​B​ ​ ​ ​h​t​t​p​s​:​/​/​d​b​.​a​m​l​l​.​d​e​v​/​
​　​　​　​　​ ​ ​A​M​L​L​ ​T​T​M​L​ ​T​o​o​l​ ​h​t​t​p​s​:​/​/​t​o​o​l​.​a​m​l​l​.​d​e​v​/​
​
​另​请​注​意​:​ ​D​e​v​T​o​o​l​s​、​插​件​、​用​户​脚​本​均​可​能​对​性​能​有​显​著​负​面​影​响​。
	 */
	consoleArt: string
}

export type TranslationFunctions = {
	editor: {
		context: {
			shared: {
				/**
				 * 复制
				 */
				copy: () => LocalizedString
				/**
				 * 剪切
				 */
				cut: () => LocalizedString
				/**
				 * 粘贴
				 */
				paste: () => LocalizedString
			}
			blank: {
				/**
				 * 插入行
				 */
				insertLine: () => LocalizedString
			}
			betweenLines: {
				/**
				 * 在此插入行
				 */
				insertLine: () => LocalizedString
			}
			line: {
				/**
				 * 设置对唱
				 */
				toggleDuet: () => LocalizedString
				/**
				 * 设置背景
				 */
				toggleBackground: () => LocalizedString
				/**
				 * 合并行
				 */
				combineLines: () => LocalizedString
				/**
				 * 在前插入行
				 */
				insertLineAbove: () => LocalizedString
				/**
				 * 在后插入行
				 */
				insertLineBelow: () => LocalizedString
				/**
				 * 克隆行
				 */
				duplicateLine: () => LocalizedString
				/**
				 * 删除行
				 */
				deleteLine: () => LocalizedString
			}
			syllable: {
				/**
				 * 在前插入音节
				 */
				insertSylBefore: () => LocalizedString
				/**
				 * 在后插入音节
				 */
				insertSylAfter: () => LocalizedString
				/**
				 * 在此拆分行
				 */
				breakLineAtSyl: () => LocalizedString
				/**
				 * 删除音节
				 */
				deleteSyl: () => LocalizedString
			}
		}
		dragGhost: {
			/**
			 * {{复制行}}
			 */
			copyLine: (arg0: number | string | boolean) => LocalizedString
			/**
			 * {{移动行}}
			 */
			moveLine: (arg0: number | string | boolean) => LocalizedString
			/**
			 * {{复制音节}}
			 */
			copySyllable: (arg0: number | string | boolean) => LocalizedString
			/**
			 * {{移动音节}}
			 */
			moveSyllable: (arg0: number | string | boolean) => LocalizedString
		}
		emptyTip: {
			title: {
				/**
				 * 没有歌词行
				 */
				noLines: () => LocalizedString
				/**
				 * 所有歌词行均为空
				 */
				allLinesEmpty: () => LocalizedString
			}
			detail: {
				/**
				 * 使用「打开」菜单加载内容，或右键空白处插入新行
				 */
				goLoadOrCreate: () => LocalizedString
				/**
				 * 使用「打开」菜单加载内容，或在内容视图下编辑
				 */
				goLoadOrEdit: () => LocalizedString
			}
		}
		line: {
			/**
			 * 行序号
			 */
			index: () => LocalizedString
			/**
			 * 双击以切换时轴忽略状态
			 */
			indexDbClickToToogleIgnore: () => LocalizedString
			/**
			 * 书签
			 */
			bookmark: () => LocalizedString
			/**
			 * 对唱
			 */
			duet: () => LocalizedString
			/**
			 * 背景
			 */
			background: () => LocalizedString
			/**
			 * 应用至逐字音译
			 */
			applyRomanToSyl: () => LocalizedString
			/**
			 * 从逐字音译生成
			 */
			generateRomanFromSyl: () => LocalizedString
			/**
			 * 行起始时间
			 */
			startTime: () => LocalizedString
			/**
			 * 行结束时间
			 */
			endTime: () => LocalizedString
			/**
			 * 点击以切换连缀结束时间
			 */
			endTimeClickToConnect: () => LocalizedString
			/**
			 * 双击以编辑
			 */
			endTimeDbClickToEdit: () => LocalizedString
			/**
			 * 连缀结束时间至下一行
			 */
			continueToNextLine: () => LocalizedString
			/**
			 * 连缀结束时间至下行
			 */
			connectNext: () => LocalizedString
			/**
			 * 添加音节
			 */
			addSyllable: () => LocalizedString
			fields: {
				/**
				 * 行翻译
				 */
				trans: () => LocalizedString
				/**
				 * 行音译
				 */
				roman: () => LocalizedString
			}
		}
		syllable: {
			/**
			 * 音节起始时间
			 */
			startTime: () => LocalizedString
			/**
			 * 音节结束时间
			 */
			endTime: () => LocalizedString
		}
		preview: {
			/**
			 * 重载 AMLL
			 */
			reloadAmll: () => LocalizedString
		}
	}
	titlebar: {
		/**
		 * 打开
		 */
		open: () => LocalizedString
		/**
		 * 打开文件
		 */
		openTip: () => LocalizedString
		openMenu: {
			/**
			 * 现有工程
			 */
			project: () => LocalizedString
			/**
			 * TTML 文件
			 */
			ttml: () => LocalizedString
			/**
			 * 粘贴 TTML
			 */
			pasteTTML: () => LocalizedString
			/**
			 * 导入纯文本
			 */
			importFromText: () => LocalizedString
			/**
			 * 导入其他格式
			 */
			importFromOtherFormats: () => LocalizedString
			/**
			 * 空项目
			 */
			blank: () => LocalizedString
		}
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 保存文件
		 */
		saveTip: () => LocalizedString
		saveMenu: {
			/**
			 * 另存为
			 */
			saveAs: () => LocalizedString
			/**
			 * 导出为项目文件
			 */
			exportToProject: () => LocalizedString
			/**
			 * 导出为 TTML 文件
			 */
			exportToTTML: () => LocalizedString
			/**
			 * 复制 TTML
			 */
			copyTTML: () => LocalizedString
			/**
			 * 导出其他格式
			 */
			exportToOtherFormats: () => LocalizedString
		}
		/**
		 * 偏好设置
		 */
		preferences: () => LocalizedString
		/**
		 * 撤销
		 */
		undo: () => LocalizedString
		/**
		 * 重做
		 */
		redo: () => LocalizedString
		view: {
			/**
			 * 内容
			 */
			content: () => LocalizedString
			/**
			 * 时轴
			 */
			timing: () => LocalizedString
			/**
			 * 预览
			 */
			preview: () => LocalizedString
		}
		saveStatus: {
			/**
			 * 兼容读写模式
			 */
			compatMode: () => LocalizedString
			/**
			 * 未授予写入权限
			 */
			permissionNotGranted: () => LocalizedString
			/**
			 * 已保存于 {0|time}
			 */
			savedAt: (arg0: Date) => LocalizedString
		}
	}
	ribbon: {
		content: {
			/**
			 * 内容
			 */
			groupLabel: () => LocalizedString
			/**
			 * 批量断字
			 */
			batchSyllabify: () => LocalizedString
			/**
			 * 打开批量断字侧边栏，将多行歌词文本拆分为音节。
			 */
			batchSyllabifyDesc: () => LocalizedString
			/**
			 * 元数据
			 */
			metadata: () => LocalizedString
			/**
			 * 打开元数据侧边栏，编辑歌词文件元数据。
			 */
			metadataDesc: () => LocalizedString
			/**
			 * 查找替换
			 */
			findReplace: () => LocalizedString
			/**
			 * 打开查找替换对话框，在歌词中查找或替换文本。
			 */
			findReplaceDesc: () => LocalizedString
		}
		lineAttr: {
			/**
			 * 行属性
			 */
			groupLabel: () => LocalizedString
			/**
			 * 对唱行
			 */
			duet: () => LocalizedString
			/**
			 * 背景行
			 */
			background: () => LocalizedString
			/**
			 * 时轴中忽略
			 */
			ignoreInTiming: () => LocalizedString
			/**
			 * 续至下行
			 */
			connectNext: () => LocalizedString
			/**
			 * 开始时间
			 */
			startTime: () => LocalizedString
			/**
			 * 结束时间
			 */
			endTime: () => LocalizedString
			/**
			 * 持续时长
			 */
			duration: () => LocalizedString
		}
		syllableAttr: {
			/**
			 * 音节属性
			 */
			groupLabel: () => LocalizedString
			/**
			 * 开始时间
			 */
			startTime: () => LocalizedString
			/**
			 * 结束时间
			 */
			endTime: () => LocalizedString
			/**
			 * 持续时长
			 */
			duration: () => LocalizedString
			/**
			 * 占位拍
			 */
			placeholdingBeat: () => LocalizedString
			/**
			 * 应用到所有相同音节
			 */
			applyToAllSameSyls: () => LocalizedString
		}
		timeShift: {
			/**
			 * 时移
			 */
			groupLabel: () => LocalizedString
			/**
			 * 延迟测试
			 */
			delayTest: () => LocalizedString
			/**
			 * 延迟
			 */
			delay: () => LocalizedString
			/**
			 * 批量时移
			 */
			batchTimeShift: () => LocalizedString
			/**
			 * 打开批量时移对话框，调整多个音节或行的时间戳。
			 */
			batchTimeShiftDesc: () => LocalizedString
		}
		view: {
			/**
			 * 视图
			 */
			groupLabel: () => LocalizedString
			/**
			 * 启用逐字音译
			 */
			enableSylRoman: () => LocalizedString
			/**
			 * 随播放自动滚动
			 */
			scrollWithPlayback: () => LocalizedString
			/**
			 * 交换行翻译音译
			 */
			swapTranslateRoman: () => LocalizedString
			/**
			 * 隐藏行翻译音译
			 */
			hideTranslateRoman: () => LocalizedString
		}
		mark: {
			/**
			 * 标记
			 */
			groupLabel: () => LocalizedString
			/**
			 * 添加书签
			 */
			addBookmark: () => LocalizedString
			/**
			 * 移除书签
			 */
			removeBookmark: () => LocalizedString
			/**
			 * 在选定行或音节上添加或移除书签。书签可以用于标记重要的部分，且不会导出到歌词文件中。
			 */
			bookmarkDesc: () => LocalizedString
			/**
			 * 添加批注
			 */
			addComment: () => LocalizedString
			/**
			 * 移除全部
			 */
			removeAll: () => LocalizedString
			/**
			 * 移除全文所有行和音节的书签与批注。您可以稍后撤销。
			 */
			removeAllDesc: () => LocalizedString
		}
		performance: {
			/**
			 * 性能
			 */
			groupLabel: () => LocalizedString
			/**
			 * 已使用
			 */
			usedHeapSize: () => LocalizedString
			/**
			 * 已分配
			 */
			totalHeapSize: () => LocalizedString
			/**
			 * 帧速率
			 */
			frameRate: () => LocalizedString
		}
	}
	sidebar: {
		syllabify: {
			/**
			 * 批量断字
			 */
			header: () => LocalizedString
			/**
			 * 选择断字引擎
			 */
			enginePlaceholder: () => LocalizedString
			/**
			 * 断字引擎
			 */
			engine: () => LocalizedString
			/**
			 * 推荐
			 */
			recommended: () => LocalizedString
			/**
			 * 不推荐
			 */
			notRecommended: () => LocalizedString
			/**
			 * 展开
			 */
			expandDesc: () => LocalizedString
			/**
			 * 收起
			 */
			collapseDesc: () => LocalizedString
			/**
			 * 自定义规则
			 */
			customRules: () => LocalizedString
			/**
			 * 区分大小写
			 */
			caseSensitive: () => LocalizedString
			/**
			 * 原始文本
			 */
			originalTextPlaceholder: () => LocalizedString
			/**
			 * 添加规则
			 */
			addRule: () => LocalizedString
			/**
			 * 现有音节属性将丢失，时长按实义字符线性插值
			 */
			sylDataLossWarn: () => LocalizedString
			/**
			 * 应用到选定行
			 */
			applyToSelectedLines: () => LocalizedString
			/**
			 * 应用到选定行及之后
			 */
			applyToLinesAndAfter: () => LocalizedString
			/**
			 * 应用到所有行
			 */
			applyToAll: () => LocalizedString
		}
		metadata: {
			/**
			 * 元数据
			 */
			header: () => LocalizedString
			/**
			 * 不使用模板
			 */
			templatePlaceholder: () => LocalizedString
			/**
			 * 元数据字段模板
			 */
			templateLabel: () => LocalizedString
			templates: {
				lrc: {
					/**
					 * LRC 元数据模板
					 */
					label: () => LocalizedString
					/**
					 * 标题
					 */
					ti: () => LocalizedString
					/**
					 * 艺术家
					 */
					ar: () => LocalizedString
					/**
					 * 专辑
					 */
					al: () => LocalizedString
					/**
					 * 作者
					 */
					au: () => LocalizedString
					/**
					 * 作词
					 */
					lr: () => LocalizedString
					/**
					 * 歌词创建者
					 */
					by: () => LocalizedString
					/**
					 * 歌词创建工具
					 */
					re: () => LocalizedString
					/**
					 * 音频长度
					 */
					len: () => LocalizedString
					/**
					 * 长度格式应为 mm:ss 或 mm:ss.sss
					 */
					lenValidationMsg: () => LocalizedString
				}
				amll: {
					/**
					 * AMLL TTML 元数据模板
					 */
					label: () => LocalizedString
					/**
					 * 歌曲名称
					 */
					musicName: () => LocalizedString
					/**
					 * 艺术家
					 */
					artists: () => LocalizedString
					/**
					 * 专辑名
					 */
					album: () => LocalizedString
					/**
					 * 网易云音乐 ID
					 */
					ncmMusicId: () => LocalizedString
					/**
					 * QQ 音乐 ID
					 */
					qqMusicId: () => LocalizedString
					/**
					 * Spotify 音乐 ID
					 */
					spotifyId: () => LocalizedString
					/**
					 * Apple Music 音乐 ID
					 */
					appleMusicId: () => LocalizedString
					/**
					 * ISRC 号
					 */
					isrc: () => LocalizedString
					/**
					 * TTML 作者 GitHub UID
					 */
					ttmlAuthorGithub: () => LocalizedString
					/**
					 * TTML 作者 GitHub 用户名
					 */
					ttmlAuthorGithubLogin: () => LocalizedString
				}
			}
			/**
			 * 文档
			 */
			documentBtn: () => LocalizedString
			/**
			 * 添加全部预设
			 */
			addAllPresets: () => LocalizedString
			/**
			 * 键名
			 */
			keyPlaceholder: () => LocalizedString
			/**
			 * 清除
			 */
			clear: () => LocalizedString
			/**
			 * 添加字段
			 */
			addField: () => LocalizedString
		}
		preference: {
			/**
			 * 偏好设置
			 */
			header: () => LocalizedString
			/**
			 * 重载页面以生效
			 */
			refreshToTakeEffect: () => LocalizedString
			resetConfirm: {
				/**
				 * 重置全部选项
				 */
				header: () => LocalizedString
				/**
				 * 确定要将所有选项恢复为默认值吗？此操作不可撤销。
				 */
				message: () => LocalizedString
				/**
				 * 重置
				 */
				action: () => LocalizedString
			}
			groups: {
				/**
				 * 数据
				 */
				data: () => LocalizedString
				/**
				 * 按键
				 */
				key: () => LocalizedString
				/**
				 * 内容
				 */
				content: () => LocalizedString
				/**
				 * 时轴
				 */
				timing: () => LocalizedString
				/**
				 * 频谱
				 */
				spectrogram: () => LocalizedString
				/**
				 * 兼容性
				 */
				compatibility: () => LocalizedString
				/**
				 * 杂项
				 */
				misc: () => LocalizedString
				/**
				 * 关于
				 */
				about: () => LocalizedString
			}
			/**
			 * 实验性选项，可能不稳定
			 */
			experimentalWarning: () => LocalizedString
			items: {
				/**
				 * 自动保存
				 */
				autoSaveEnabled: () => LocalizedString
				/**
				 * 授予写入权限后，定时保存至文件系统
				 */
				autoSaveEnabledDesc: () => LocalizedString
				/**
				 * 自动保存间隔
				 */
				autoSaveIntervalMinutes: () => LocalizedString
				/**
				 * 自动保存触发的时间间隔 (分钟)
				 */
				autoSaveIntervalMinutesDesc: () => LocalizedString
				/**
				 * 历史记录快照数
				 */
				maxUndoSteps: () => LocalizedString
				/**
				 * 允许撤销的最大操作步数
				 */
				maxUndoStepsDesc: () => LocalizedString
				/**
				 * 将音频嵌入项目文件
				 */
				packAudioToProject: () => LocalizedString
				/**
				 * 将音频文件打包在项目文件中，以便归档或分享
				 */
				packAudioToProjectDesc: () => LocalizedString
				/**
				 * 以 TTML 为默认格式
				 */
				ttmlAsDefault: () => LocalizedString
				/**
				 * 新建和保存文档时默认使用 TTML 而非 ALP 格式
				 */
				ttmlAsDefaultDesc: () => LocalizedString
				/**
				 * 打开文件时请求写权限
				 */
				askPermissionOnOpen: () => LocalizedString
				/**
				 * 打开文件时立即请求写入权限，以启用自动保存
				 */
				askPermissionOnOpenDesc: () => LocalizedString
				/**
				 * 按键绑定
				 */
				keyBinding: () => LocalizedString
				/**
				 * 打开快捷键设置窗口
				 */
				keyBindingDesc: () => LocalizedString
				/**
				 * 设置
				 */
				keyBindingAction: () => LocalizedString
				/**
				 * macOS 风格组合键
				 */
				macStyleShortcuts: () => LocalizedString
				/**
				 * 使用 ⌘、⌥ 等符号展示组合键
				 */
				macStyleShortcutsDesc: () => LocalizedString
				/**
				 * 音频按键跳转步长
				 */
				audioSeekingStepMs: () => LocalizedString
				/**
				 * 按键快进或快退时跳转的时长 (毫秒)
				 */
				audioSeekingStepMsDesc: () => LocalizedString
				/**
				 * 交换翻译与音译框位置
				 */
				swapTranslateRoman: () => LocalizedString
				/**
				 * 在内容视图将音译框置于左侧，并影响查找顺序
				 */
				swapTranslateRomanDesc: () => LocalizedString
				/**
				 * 隐藏翻译音译框
				 */
				hideTranslateRoman: () => LocalizedString
				/**
				 * 隐藏内容视图中的翻译音译框
				 */
				hideTranslateRomanDesc: () => LocalizedString
				/**
				 * 启用逐字音译
				 */
				sylRomanEnabled: () => LocalizedString
				/**
				 * 在音节框下方显示逐字音译，并支持查找替换
				 */
				sylRomanEnabledDesc: () => LocalizedString
				/**
				 * 全局延时补偿
				 */
				globalLatencyMs: () => LocalizedString
				/**
				 * 正值表示实际音频落后 (毫秒)
				 */
				globalLatencyMsDesc: () => LocalizedString
				/**
				 * 始终忽略背景行
				 */
				alwaysIgnoreBackground: () => LocalizedString
				/**
				 * 在时轴页上始终跳过背景行
				 */
				alwaysIgnoreBackgroundDesc: () => LocalizedString
				/**
				 * 隐藏行时间戳
				 */
				hideLineTiming: () => LocalizedString
				/**
				 * 自动从音节生成行时间戳
				 */
				hideLineTimingDesc: () => LocalizedString
				/**
				 * 随播放自动滚动
				 */
				scrollWithPlayback: () => LocalizedString
				/**
				 * 时轴视图中随播放进度自动滚动
				 */
				scrollWithPlaybackDesc: () => LocalizedString
				/**
				 * 进度条高亮选中行
				 */
				highlightSelectedLineOnProgress: () => LocalizedString
				/**
				 * 在进度波形条上高亮显示当前选中行的时间段
				 */
				highlightSelectedLineOnProgressDesc: () => LocalizedString
				/**
				 * 兼容性报告
				 */
				compatibilityReport: () => LocalizedString
				/**
				 * 打开兼容性报告窗口
				 */
				compatibilityReportDesc: () => LocalizedString
				/**
				 * 打开
				 */
				compatibilityReportAction: () => LocalizedString
				/**
				 * 启动时报告兼容性问题
				 */
				notifyCompatIssuesOnStartup: () => LocalizedString
				/**
				 * 在启动时若发现问题，显示兼容性报告对话框
				 */
				notifyCompatIssuesOnStartupDesc: () => LocalizedString
				/**
				 * 重置全部选项
				 */
				resetAll: () => LocalizedString
				/**
				 * 将所有选项恢复为默认值
				 */
				resetAllDesc: () => LocalizedString
				/**
				 * 语言
				 */
				language: () => LocalizedString
				/**
				 * 选择界面显示语言
				 */
				languageDesc: () => LocalizedString
				/**
				 * 重置
				 */
				resetAllAction: () => LocalizedString
				/**
				 * 关于 {0}
				 */
				aboutApp: (arg0: unknown) => LocalizedString
				/**
				 * 打开软件版本信息窗口
				 */
				aboutAppDesc: () => LocalizedString
				/**
				 * 关于
				 */
				aboutAppAction: () => LocalizedString
				/**
				 * GitHub 仓库
				 */
				githubRepo: () => LocalizedString
				/**
				 * 访问源代码仓库页面
				 */
				githubRepoDesc: () => LocalizedString
				/**
				 * 前往
				 */
				githubRepoAction: () => LocalizedString
				/**
				 * 侧边栏宽度
				 */
				sidebarWidth: () => LocalizedString
				/**
				 * 侧边栏的默认宽度 (像素)
				 */
				sidebarWidthDesc: () => LocalizedString
				/**
				 * 频谱图高度
				 */
				spectrogramHeight: () => LocalizedString
				/**
				 * 频谱图的高度 (像素)
				 */
				spectrogramHeightDesc: () => LocalizedString
				/**
				 * 配色方案
				 */
				spectrogramColor: () => LocalizedString
				/**
				 * 选择预设色彩方案或自定义渐变
				 */
				spectrogramColorDesc: () => LocalizedString
			}
		}
	}
	player: {
		/**
		 * 选择音频文件
		 */
		chooseAudioFile: () => LocalizedString
		/**
		 * 播放选项
		 */
		playOptions: () => LocalizedString
		/**
		 * 使用鼠标滚轮调整音量
		 */
		playOptionsWheel: () => LocalizedString
		/**
		 * 音量
		 */
		volume: () => LocalizedString
		/**
		 * 速率
		 */
		rate: () => LocalizedString
		/**
		 * 重置到 {0}
		 */
		resetTo: (arg0: unknown) => LocalizedString
		/**
		 * 播放
		 */
		play: () => LocalizedString
		/**
		 * 暂停
		 */
		pause: () => LocalizedString
		/**
		 * 显示频谱图
		 */
		showSpectrogram: () => LocalizedString
		/**
		 * 隐藏频谱图
		 */
		hideSpectrogram: () => LocalizedString
		/**
		 * 频谱图不可用
		 */
		spectrogramUnavailable: () => LocalizedString
		/**
		 * 所有支持的音频格式
		 */
		allSupportedFormats: () => LocalizedString
		failedToLoadAudio: {
			/**
			 * 加载音频失败
			 */
			summary: () => LocalizedString
			/**
			 * 文件访问被用户或平台拒绝
			 */
			detailAborted: () => LocalizedString
		}
		/**
		 * 成功加载音频
		 */
		loadAudioSuccess: () => LocalizedString
	}
	spectrogram: {
		emptyTip: {
			/**
			 * 没有音频数据
			 */
			title: () => LocalizedString
			/**
			 * 加载音频文件后将渲染频谱图
			 */
			detail: () => LocalizedString
		}
	}
	compat: {
		dialog: {
			/**
			 * 兼容性报告
			 */
			header: () => LocalizedString
			/**
			 * 不支持
			 */
			notSupported: () => LocalizedString
			/**
			 * 未提供说明
			 */
			noReasonProvided: () => LocalizedString
			/**
			 * 未提供可能导致的问题
			 */
			noImpactProvided: () => LocalizedString
			/**
			 * 启动时不再检查兼容性
			 */
			dontCheckOnStartup: () => LocalizedString
			/**
			 * 确认
			 */
			proceed: () => LocalizedString
		}
		sharedReasons: {
			/**
			 * 未在安全上下文中运行。需要 HTTPS 或从本地回环访问。
			 */
			insecureContext: () => LocalizedString
		}
		clipboard: {
			/**
			 * 剪贴板 API
			 */
			name: () => LocalizedString
			/**
			 * 剪贴板 API (Clipboard API) 允许网页在用户授权后读写系统剪贴板的内容。
			 */
			description: () => LocalizedString
			/**
			 * 剪切复制粘贴歌词行与音节、复制和粘贴 TTML 功能不可用。
			 */
			impact: () => LocalizedString
			/**
			 * 浏览器不支持剪贴板相关的 API。此 API 在 Chromium 66、Firefox 125、Safari 13.1 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		fileSystem: {
			/**
			 * 文件系统 API
			 */
			name: () => LocalizedString
			/**
			 * 文件系统 API (File System API) 允许网页在用户授权后读写磁盘上的文件，提供接近原生的文件操作能力。
			 */
			description: () => LocalizedString
			/**
			 * 保存文件时无法直接写入，而是通过浏览器下载；自动保存不可用。
			 */
			impact: () => LocalizedString
			/**
			 * 浏览器不支持文件系统相关的 API。此 API 在 Chromium 86 及以上版本中支持，Firefox 和 Safari 暂不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		mediaSession: {
			/**
			 * 媒体会话 API
			 */
			name: () => LocalizedString
			/**
			 * 媒体会话 (Media Session) 允许网页自定义媒体通知和响应媒体键事件。
			 */
			description: () => LocalizedString
			/**
			 * 将不能从系统媒体控制界面（如锁屏界面或通知中心）控制媒体播放。
			 */
			impact: () => LocalizedString
			/**
			 * 浏览器不支持媒体会话相关的 API。此 API 在 Chromium 72、Firefox 82、Safari 15 或以上版本中支持。Firefox Android 目前不支持。
			 */
			apiNotSupported: () => LocalizedString
		}
		sharedArrayBuffer: {
			/**
			 * 共享内存缓冲区
			 */
			name: () => LocalizedString
			/**
			 * 共享内存缓冲区 (Shared Array Buffer) 允许在多个线程间高效共享数据。
			 */
			description: () => LocalizedString
			/**
			 * 频谱图功能不可用。
			 */
			impact: () => LocalizedString
			/**
			 * 浏览器不支持 SharedArrayBuffer。此 API 在 Chromium 68、Firefox 79、Safari 15.2 或以上版本中支持。
			 */
			apiNotSupported: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。请联系部署方提供对应的 HTTP 响应头，或调整构建选项以启用 Service Worker 方式实现的跨源隔离。
			 */
			coiRequired: () => LocalizedString
			/**
			 * 未启用跨源隔离 (COOP/COEP)。此部署已尝试通过 Service Worker 启用跨源隔离。若未生效，请尝试刷新页面。
			 */
			coiWorkaround: () => LocalizedString
		}
	}
	formats: {
		sharedReferences: {
			/**
			 * 维基百科
			 */
			wikipedia: () => LocalizedString
			/**
			 * 官方文档
			 */
			officialDoc: () => LocalizedString
		}
		alp: {
			/**
			 * AMLL Editor 工程
			 */
			name: () => LocalizedString
			/**
			 * AMLL Editor 的项目文件格式，内嵌音频文件和歌词数据，适合项目保存和传输。
			 */
			description: () => LocalizedString
		}
		ttml: {
			/**
			 * AMLL TTML
			 */
			name: () => LocalizedString
			/**
			 * 基于 W3C TTML 标准的歌词格式，遵循 AMLL TTML 歌词格式规范。
			 */
			description: () => LocalizedString
		}
		lrc: {
			/**
			 * 基本 LRC
			 */
			name: () => LocalizedString
			/**
			 * 最常见的歌词格式。支持行时间戳，不支持逐字时间戳。此处指基本 LRC 格式，若要导入基于 LRC 的扩展格式，请选择对应扩展格式选项。
			 */
			description: () => LocalizedString
		}
		lrcA2: {
			/**
			 * LRC A2 扩展
			 */
			name: () => LocalizedString
			/**
			 * 基于 LRC 的扩展格式，支持行时间戳和逐字时间戳，最早由 A2 Media Player 提出。
			 */
			description: () => LocalizedString
		}
		yrc: {
			/**
			 * 网易云逐字
			 */
			name: () => LocalizedString
			/**
			 * 网易云音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		qrc: {
			/**
			 * QQ 音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * QQ 音乐的私有逐字歌词格式。支持行时间戳和逐字时间戳。
			 */
			description: () => LocalizedString
		}
		lyl: {
			/**
			 * Lyricify Lines
			 */
			name: () => LocalizedString
			/**
			 * Lyricify 的私有行时间戳歌词格式，不支持逐字时间戳。
			 */
			description: () => LocalizedString
		}
		lys: {
			/**
			 * Lyricify Syllable
			 */
			name: () => LocalizedString
			/**
			 * Lyricify 的私有逐字时间戳歌词格式，支持逐字、背景与对唱。
			 */
			description: () => LocalizedString
		}
		lqe: {
			/**
			 * Lyricify 快速导出
			 */
			name: () => LocalizedString
			/**
			 * Lyricify 的私有快速导出格式，在 Lyricify Syllable 逐字基础上支持翻译与音译。
			 */
			description: () => LocalizedString
		}
		spl: {
			/**
			 * 椒盐音乐逐字
			 */
			name: () => LocalizedString
			/**
			 * 椒盐音乐的私有格式，基于 LRC 扩展，支持行时间戳和逐字时间戳，并支持翻译。由于规则繁杂，可能不完全可用。
			 */
			description: () => LocalizedString
		}
	}
	file: {
		/**
		 * 所有支持的格式
		 */
		allSupportedFormats: () => LocalizedString
		/**
		 * 未命名
		 */
		untitled: () => LocalizedString
		/**
		 * 成功加载文件
		 */
		loaded: () => LocalizedString
		failedToReadErr: {
			/**
			 * 读取文件失败
			 */
			summary: () => LocalizedString
			/**
			 * 不支持的文件类型：{0}
			 */
			typeNotSupported: (arg0: unknown) => LocalizedString
		}
		dataDropConfirm: {
			/**
			 * 您有未保存的工作
			 */
			header: () => LocalizedString
			/**
			 * 如果继续，所有未保存的更改将会丢失。此操作不可撤销。
			 */
			message: () => LocalizedString
			/**
			 * 继续
			 */
			acceptLabel: () => LocalizedString
		}
		/**
		 * 成功加载文件
		 */
		loadFileSuccess: () => LocalizedString
		failedToLoadErr: {
			/**
			 * 加载文件失败
			 */
			summary: () => LocalizedString
			/**
			 * 文件访问被用户或平台拒绝
			 */
			detailAborted: () => LocalizedString
		}
		/**
		 * 剪贴板为空
		 */
		clipboardIsEmptyErr: () => LocalizedString
		/**
		 * 从剪贴板导入 TTML 失败
		 */
		failedToPasteTTML: () => LocalizedString
		/**
		 * 复制 TTML 到剪贴板失败
		 */
		failedToCopyTTML: () => LocalizedString
		/**
		 * 成功从剪贴板导入 TTML
		 */
		pasteTTMLSuccess: () => LocalizedString
		/**
		 * 成功复制 TTML 到剪贴板
		 */
		copyTTMLSuccess: () => LocalizedString
		/**
		 * 成功创建空项目
		 */
		newBlankProjectSuccess: () => LocalizedString
		failedBlankProject: {
			/**
			 * 创建空项目失败
			 */
			summary: () => LocalizedString
			/**
			 * 操作被用户拒绝
			 */
			detailAborted: () => LocalizedString
		}
		/**
		 * 成功保存文件
		 */
		saveFileSuccess: () => LocalizedString
		failedToSaveErr: {
			/**
			 * 保存文件失败
			 */
			summary: () => LocalizedString
			/**
			 * 文件写入被用户或平台拒绝
			 */
			detailAborted: () => LocalizedString
		}
		/**
		 * 成功另存为文件
		 */
		saveAsSuccess: () => LocalizedString
		failedToSaveAsErr: {
			/**
			 * 另存为文件失败
			 */
			summary: () => LocalizedString
			/**
			 * 文件写入被用户或平台拒绝
			 */
			detailAborted: () => LocalizedString
		}
	}
	find: {
		/**
		 * 查找替换
		 */
		header: () => LocalizedString
		mode: {
			/**
			 * 查找
			 */
			find: () => LocalizedString
			/**
			 * 替换
			 */
			replace: () => LocalizedString
		}
		placeholder: {
			/**
			 * 查找内容
			 */
			find: () => LocalizedString
			/**
			 * 替换为
			 */
			replace: () => LocalizedString
		}
		/**
		 * 更多选项
		 */
		moreOptionSwitch: () => LocalizedString
		/**
		 * 匹配选项
		 */
		optionsHeader: () => LocalizedString
		options: {
			/**
			 * 区分大小写
			 */
			caseSensitive: () => LocalizedString
			/**
			 * 全字匹配
			 */
			wholeWord: () => LocalizedString
			/**
			 * 全字段匹配
			 */
			wholeField: () => LocalizedString
			/**
			 * 跨音节匹配
			 */
			crossSyl: () => LocalizedString
			/**
			 * 正则表达式
			 */
			useRegex: () => LocalizedString
			/**
			 * 循环搜索
			 */
			loopSearch: () => LocalizedString
		}
		/**
		 * 匹配范围
		 */
		scopeHeader: () => LocalizedString
		scope: {
			/**
			 * 音节内容
			 */
			sylContent: () => LocalizedString
			/**
			 * 音节音译
			 */
			sylRoman: () => LocalizedString
			/**
			 * 翻译
			 */
			trans: () => LocalizedString
			/**
			 * 音译
			 */
			roman: () => LocalizedString
			/**
			 * 行音译
			 */
			lineRoman: () => LocalizedString
			/**
			 * 行翻译
			 */
			lineTrans: () => LocalizedString
		}
		actions: {
			/**
			 * 替换
			 */
			replace: () => LocalizedString
			/**
			 * 全部替换
			 */
			replaceAll: () => LocalizedString
			/**
			 * 查找上一项
			 */
			findPrev: () => LocalizedString
			/**
			 * 查找下一项
			 */
			findNext: () => LocalizedString
		}
		infLoopErr: {
			/**
			 * 搜索失败
			 */
			summary: () => LocalizedString
			/**
			 * 发生死循环。请前往反馈此问题。
			 */
			detail: () => LocalizedString
		}
		noResultWarn: {
			/**
			 * 找不到结果
			 */
			summary: () => LocalizedString
			/**
			 * 在所选范围内文档为空。
			 */
			detailEmpty: () => LocalizedString
			/**
			 * 全文搜索完毕，未找到匹配项。
			 */
			detailNoMatch: () => LocalizedString
			/**
			 * 已到达文档末端，无匹配项。
		启用循环搜索可从头开始继续搜索。
			 */
			detailNoMatchEnd: () => LocalizedString
		}
		replaceSuccess: {
			/**
			 * 替换成功
			 */
			summary: () => LocalizedString
			/**
			 * 共替换了 {0} 处匹配项。
			 */
			detail: (arg0: number) => LocalizedString
		}
	}
	hotkey: {
		/**
		 * 按键绑定
		 */
		dialogHeader: () => LocalizedString
		/**
		 * 未绑定
		 */
		notBinded: () => LocalizedString
		btns: {
			/**
			 * 添加
			 */
			add: () => LocalizedString
			/**
			 * 移除
			 */
			del: () => LocalizedString
			/**
			 * 重置为默认
			 */
			reset: () => LocalizedString
		}
		groupTitles: {
			/**
			 * 文件操作
			 */
			file: () => LocalizedString
			/**
			 * 视图与界面
			 */
			view: () => LocalizedString
			/**
			 * 编辑操作
			 */
			editing: () => LocalizedString
			/**
			 * 时轴
			 */
			timing: () => LocalizedString
			/**
			 * 音频控制
			 */
			audio: () => LocalizedString
		}
		commands: {
			/**
			 * 打开
			 */
			open: () => LocalizedString
			/**
			 * 保存
			 */
			save: () => LocalizedString
			/**
			 * 另存为
			 */
			saveAs: () => LocalizedString
			/**
			 * 新建空项目
			 */
			'new': () => LocalizedString
			/**
			 * 导出到剪贴板
			 */
			exportToClipboard: () => LocalizedString
			/**
			 * 从剪贴板导入
			 */
			importFromClipboard: () => LocalizedString
			/**
			 * 切换到内容视图
			 */
			switchToContent: () => LocalizedString
			/**
			 * 切换到时轴视图
			 */
			switchToTiming: () => LocalizedString
			/**
			 * 切换到预览视图
			 */
			switchToPreview: () => LocalizedString
			/**
			 * 偏好设置
			 */
			preferences: () => LocalizedString
			/**
			 * 批量断字
			 */
			batchSplitText: () => LocalizedString
			/**
			 * 元数据
			 */
			metadata: () => LocalizedString
			/**
			 * 批量时移
			 */
			batchTimeShift: () => LocalizedString
			/**
			 * 撤销
			 */
			undo: () => LocalizedString
			/**
			 * 重做
			 */
			redo: () => LocalizedString
			/**
			 * 书签
			 */
			bookmark: () => LocalizedString
			/**
			 * 查找
			 */
			find: () => LocalizedString
			/**
			 * 替换
			 */
			replace: () => LocalizedString
			/**
			 * 删除
			 */
			'delete': () => LocalizedString
			/**
			 * 全选所有行
			 */
			selectAllLines: () => LocalizedString
			/**
			 * 全选所有音节
			 */
			selectAllSyls: () => LocalizedString
			/**
			 * 拆分行
			 */
			breakLine: () => LocalizedString
			/**
			 * 设为对唱行
			 */
			duet: () => LocalizedString
			/**
			 * 设为背景行
			 */
			background: () => LocalizedString
			/**
			 * 续至下行
			 */
			connectNextLine: () => LocalizedString
			/**
			 * 合并行
			 */
			combineLines: () => LocalizedString
			/**
			 * 上一行
			 */
			goPrevLine: () => LocalizedString
			/**
			 * 上一音节
			 */
			goPrevSyl: () => LocalizedString
			/**
			 * 上一音节并播放
			 */
			goPrevSylnPlay: () => LocalizedString
			/**
			 * 下一行
			 */
			goNextLine: () => LocalizedString
			/**
			 * 下一音节
			 */
			goNextSyl: () => LocalizedString
			/**
			 * 下一音节并播放
			 */
			goNextSylnPlay: () => LocalizedString
			/**
			 * 播放当前音节
			 */
			playCurrSyl: () => LocalizedString
			/**
			 * 标记开始时间
			 */
			markBegin: () => LocalizedString
			/**
			 * 标记连缀时间
			 */
			markEndBegin: () => LocalizedString
			/**
			 * 标记结束时间
			 */
			markEnd: () => LocalizedString
			/**
			 * 选择媒体
			 */
			chooseMedia: () => LocalizedString
			/**
			 * 快退
			 */
			seekBackward: () => LocalizedString
			/**
			 * 增大音量
			 */
			volumeUp: () => LocalizedString
			/**
			 * 播放/暂停音频
			 */
			playPauseAudio: () => LocalizedString
			/**
			 * 快进
			 */
			seekForward: () => LocalizedString
			/**
			 * 减小音量
			 */
			volumeDown: () => LocalizedString
		}
		keyNames: {
			/**
			 * 空格
			 */
			space: () => LocalizedString
		}
	}
	syllabify: {
		engines: {
			basic: {
				/**
				 * 基本断字
				 */
				name: () => LocalizedString
				/**
				 * 对西文按词拆分，对于 CJK 按字拆分。若有自定义规则，将对拆分后的词应用，已拆分的词不会合并。
				 */
				description: () => LocalizedString
			}
			jaBasic: {
				/**
				 * 日语基本断字
				 */
				name: () => LocalizedString
				/**
				 * 针对日语拗音等做专门处理。若有自定义规则，将优先提取自定义拆分，其余部分按规则拆分。
				 */
				description: () => LocalizedString
			}
			prosodic: {
				/**
				 * 英语 (Prosodic)
				 */
				name: () => LocalizedString
				/**
				 * 将 SUBTLEXus 作为语料，由 Prosodic 根据读音进行音节划分并匹配回拼写得到词典，高频词经人工校对。未命中的词将回退至 Compromise。
				 */
				description: () => LocalizedString
			}
			silabas: {
				/**
				 * 西班牙语 (Silabas)
				 */
				name: () => LocalizedString
				/**
				 * 由 Silabas.js 库提供的西班牙语正字法音节切分，基于现代语料。移植自 ULPGC Silabeador TIP C++ 实现。
				 */
				description: () => LocalizedString
			}
			silabeador: {
				/**
				 * 西班牙语 (Silabeador)
				 */
				name: () => LocalizedString
				/**
				 * 由 Silabeador 库提供，主要基于黄金时代语料的西班牙语正字法音节切分，与现代规则有一定出入。通过 Pyodide 运行，初次加载可能较慢。
				 */
				description: () => LocalizedString
			}
			compromise: {
				/**
				 * 英语 (Compromise)
				 */
				name: () => LocalizedString
				/**
				 * 由 Compromise 库提供的纯正字法英语音节拆分。由于英语发音不规则情况较多，请优先使用 Prosodic 引擎。
				 */
				description: () => LocalizedString
			}
			syllabifyFr: {
				/**
				 * 法语 (Syllabify-fr)
				 */
				name: () => LocalizedString
				/**
				 * 由 Syllabify-fr 库提供的正字法法语音节划分。
				 */
				description: () => LocalizedString
			}
			syllabify: {
				/**
				 * 俄语 (Syllabify)
				 */
				name: () => LocalizedString
				/**
				 * 由 Syllabify 库提供的正字法俄语音节划分。
				 */
				description: () => LocalizedString
			}
			none: {
				/**
				 * 不断字
				 */
				name: () => LocalizedString
				/**
				 * 不进行音节划分，将每行的所有文本合并为一个音节。自定义规则不产生作用。适用于制作逐行歌词。
				 */
				description: () => LocalizedString
			}
		}
	}
	components: {
		confirmDialog: {
			/**
			 * 取消
			 */
			cancel: () => LocalizedString
			/**
			 * 继续
			 */
			'continue': () => LocalizedString
		}
		/**
		 * 当前视图无内容可显示
		 */
		emptyTipDefault: () => LocalizedString
	}
	importFromText: {
		/**
		 * 从纯文本导入
		 */
		header: () => LocalizedString
		modes: {
			/**
			 * 分别输入
			 */
			separate: () => LocalizedString
			/**
			 * 歌词原文、翻译、音译分别在不同的文本框中输入。相同位置的行为一组。
			 */
			separateDesc: () => LocalizedString
			/**
			 * 交错行
			 */
			interleaved: () => LocalizedString
			/**
			 * 歌词原文与翻译、音译行混合交错排列。每连续的数行为一组。
			 */
			interleavedDesc: () => LocalizedString
		}
		fields: {
			/**
			 * 原文
			 */
			original: () => LocalizedString
			/**
			 * （保留现有行）
			 */
			keepCurrentLinesTip: () => LocalizedString
			/**
			 * 翻译
			 */
			trans: () => LocalizedString
			/**
			 * 音译
			 */
			roman: () => LocalizedString
			/**
			 * 至少提供一项
			 */
			atLeastProvideOne: () => LocalizedString
		}
		toolBtns: {
			/**
			 * 移除时间戳
			 */
			removeTimestamps: () => LocalizedString
			/**
			 * 移除空白行
			 */
			removeEmptyLines: () => LocalizedString
			/**
			 * 规范化空格
			 */
			normalizeSpaces: () => LocalizedString
			/**
			 * 首字母大写
			 */
			capitalizeFirstLetter: () => LocalizedString
			/**
			 * 去除尾标点
			 */
			removeTrailingPunc: () => LocalizedString
		}
		lineOrder: {
			/**
			 * 行顺序设置
			 */
			header: () => LocalizedString
			/**
			 * 当前循环节共 {0} 行
			 */
			cycleLengthHint: (arg0: number) => LocalizedString
			/**
			 * 原文行
			 */
			original: () => LocalizedString
			/**
			 * 翻译行
			 */
			trans: () => LocalizedString
			/**
			 * 音译行
			 */
			roman: () => LocalizedString
			/**
			 * 组间空行数
			 */
			emptyLineCount: () => LocalizedString
		}
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 导入
		 */
		action: () => LocalizedString
	}
	importFromOtherFormats: {
		/**
		 * 从其他歌词格式导入
		 */
		header: () => LocalizedString
		/**
		 * 未提供说明
		 */
		noDescriptionProvided: () => LocalizedString
		/**
		 * 显示示例
		 */
		showExamples: () => LocalizedString
		/**
		 * 从文件打开
		 */
		fromFile: () => LocalizedString
		/**
		 * 示例格式
		 */
		exampleLabel: () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 导入
		 */
		'import': () => LocalizedString
		/**
		 * 请在左侧选择格式
		 */
		requireSelectFormat: () => LocalizedString
	}
	about: {
		/**
		 * 关于
		 */
		header: () => LocalizedString
		/**
		 * 版本
		 */
		version: () => LocalizedString
		/**
		 * 基于 Vue 的开源逐音节歌词编辑器，可与 AMLL 生态软件协作，目标成为 AMLL TTML Tool 的继任者。
	开发不易，不妨点个免费的 star 吧！
		 */
		description: () => LocalizedString
		/**
		 * GitHub 仓库
		 */
		githubBtn: () => LocalizedString
		/**
		 * 展开详细信息
		 */
		detailBtn: () => LocalizedString
		detail: {
			/**
			 * 版本号
			 */
			version: () => LocalizedString
			/**
			 * 构建通道
			 */
			channel: () => LocalizedString
			/**
			 * 提交哈希
			 */
			hash: () => LocalizedString
			/**
			 * 构建时间
			 */
			buildTime: () => LocalizedString
			/**
			 * AMLL 核心版本
			 */
			amllCoreVersion: () => LocalizedString
			/**
			 * AMLL Vue 版本
			 */
			amllVueVersion: () => LocalizedString
			/**
			 * 未指定
			 */
			notSpecified: () => LocalizedString
		}
	}
	batchTimeShift: {
		/**
		 * 批量时移
		 */
		header: () => LocalizedString
		/**
		 * 推迟为正，提前为负
		 */
		signHint: () => LocalizedString
		/**
		 * 应用到选定音节
		 */
		applyToSyl: () => LocalizedString
		/**
		 * 应用到选定行
		 */
		applyToLine: () => LocalizedString
		/**
		 * 应用到全文
		 */
		applyToAll: () => LocalizedString
	}
	/**
	 * ╭──────────╮       ╶╴    ┌─╴  ╶─┐┌─┐    ┌─┐      ┌─────┐    ┌─┐┌─┐
│ ━━━━━━   │      ╱  ╲   │  ╲╱  ││ │    │ │      │ ┌───┘    │ │└─┘┌─┐
│   ━━━━━  │     ╱ ╱╲ ╲  │ ╷  ╷ ││ │    │ │      │ └──┐ ╭───┘ │┌─┐│ └┐╭─────╮╭───┐
│ |> ━━━ • │    ╱ ╶──╴ ╲ │ │╲╱│ ││ │    │ │      │ ┌──┘ │ ╭─╮ ││ ││ ┌┘│ ╭─╮ ││ ┌─┘
│   ━━━━━  │   ╱ ╱    ╲ ╲│ │  │ ││ └───┐│ └───┐  │ └───┐│ ╰─╯ ││ ││ └┐│ ╰─╯ ││ │
╰──────────╯   ─╴      ╶─└─┘  └─┘└─────┘└─────┘  └─────┘╰─────┘└─┘╰──┘╰─────╯└─┘

喜欢您来！

项目地址: https://github.com/amll-dev/amll-editor
　　　　  以 AGPLv3 only 许可证开源

友情链接: AMLL Homepage  https://amll.dev/
　　　　  AMLL TTML DB   https://db.amll.dev/
　　　　  AMLL TTML Tool https://tool.amll.dev/

另请注意: DevTools、插件、用户脚本均可能对性能有显著负面影响。
	 */
	consoleArt: () => LocalizedString
}

export type Formatters = {
	time: (value: Date) => unknown
}
